### ISSUE TITLE
Add acknowledgments section

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#109]
Originally filed as [bug 27725](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27725).

There was some work done in that bug. There may be more names to add, including from GitHub participants.

**Comment by ashimura** [comment]
Sorry we didn't contact you earlier, but as I sent by email to you, the Web and TV Interest Group (IG) would like you to consider the contribution from the IG for the Encrypted Media Extensions
specification too.

As you know, the IG sent requirements for <a href="https://www.w3.org/TR/encrypted-media/">EME</a> and <a href="https://www.w3.org/TR/media-source/">MSE</a> specifications several years ago, and we're wondering if our contributors' names could be also included in the Acknowledgements sections of the EME specification.

We think it would make sense to ask you to add the names of the following 18 participants in the Web and TV IG's MPTF TF to the EME Acknowledgements section:

<ul>
<li>Clarke Stevens, CableLabs (MPTF moderator)</li>
<li>Hiroyuki Aizu, Toshiba</li>
<li>Kaz Ashimura, W3C</li>
<li>Richard Bardini, Intel</li>
<li>Russell Berkoff, Samsung Electronics</li>
<li>Pablo Cesar, CWI</li>
<li>David Corvoysier, Orange</li>
<li>Francois Daoust, W3C</li>
<li>Franck Denoual, Canon Research Centre France</li>
<li>Davy Van Deursen, Ghent University, IBBT</li>
<li>Jean-Claude Dufourd, Telecom Paristech</li>
<li>Jerry Ezrol, AT&amp;T</li>
<li>Narm Gadiraju, Intel</li>
<li>Juhani Huttunen, Nokia</li>
<li>Hyeonjae Lee, LG Electronics</li>
<li>Jan Lindquist, Ericsson</li>
<li>Nilo Mitra, Ericsson</li>
<li>Youngsun Ryu, Samsung</li>
</ul>

Similarly, it would be great if you could consider the following 21 MPTF participants as contributors for the MSE specification:

<ul>
<li>Clarke Stevens, CableLabs (MPTF moderator)</li>
<li>Hiroyuki Aizu, Toshiba </li>
<li>Kaz Ashimura, W3C </li>
<li>Richard Bardini, Intel</li>
<li>Russell Berkoff, Samsung Electronics</li>
<li>Pablo Cesar, CWI</li>
<li>David Corvoysier, Orange</li>
<li>Francois Daoust, W3C</li>
<li>Franck Denoual, Canon Research Centre France</li>
<li>Davy Van Deursen, Ghent University, IBBT</li>
<li>Jean-Claude Dufourd, Telecom Paristech</li>
<li>Jerry Ezrol, AT&amp;T</li>
<li>Narm Gadiraju, Intel</li>
<li>Juhani Huttunen, Nokia</li>
<li>Hyeonjae Lee, LG Electronics</li>
<li>Jason Lewis, Disney</li>
<li>Jan Lindquist, Ericsson</li>
<li>David Mays, Comcast</li>
<li>Nilo Mitra, Ericsson</li>
<li>Giuseppe Pascale, Opera</li>
<li>Youngsun Ryu, Samsung Electronics</li>
</ul>

Given the style of the Acknowledgements section at https://www.w3.org/TR/encrypted-media/#acknowledgements, putting only the names (without affiliations) might be appropriate.

Please note that we have installed our proposed requirements documents for EME and MSE on the W3C server as follows:

<ul>
<li><a href="https://www.w3.org/2011/webtv/MPTF/adbreq.html">MPTF Requirements for Adaptive Bit Rate Streaming</a></li>
<li><a href="https://www.w3.org/2011/webtv/MPTF/cpreq.html">MPTF Requirements for Content Protection</a></li>
</ul>

Those requirements documents were originally maintained on the dvcs.w3.org server, but there was some trouble with CSS styling. Also the links should be permanent. So we have moved those files to the www.w3.org server under the Web and TV IG area as above.

It would be really appreciated if you could add links to those documents as well to the EME/MSE specifications.

Thanks,

Kazuyuki Ashimura, Web and TV IG Team Contact

**Comment by mavgit** [comment]
Thanks, Kaz.

FYI, the MPTF participants were the same for both specs. The lists above are different based on doing a diff with the current Acknowledgements sections of the two specs, since different MPTF participants are already acknowledged in the two specs..

**Comment by jdsmith3000** [comment]
I've copied the list of MSE names to https://github.com/w3c/media-source/issues/48.  I'll handle the other ones on this bug.

I'm not sure linking the MPTF specs should be done.  The use case requirements in them appear to be substantially met, but we've not made any clear reference to them from either the EME or MSE specifications.

**Comment by mavgit** [comment]
> I'm not sure linking the MPTF specs should be done. The use case requirements in them appear to be  substantially met, but we've not made any clear reference to them from either the EME or MSE  specifications.

To be clear, I do not think the MPTF specs should be linked as Normative references nor in any way that implies they represent the current requirements for EME or MSE.

I do think the two MPTF specs should be linked in a non-normative manner to provide a record of the history of the projects. 

- EME work directly flowed from MPTF work summarized in [MPTF Requirements for Content Protection](https://www.w3.org/2011/webtv/MPTF/cpreq.html)
- MSE work directly flowed from MPTF work summarized in [MPTF Requirements for Adaptive Bit Rate Streaming](https://www.w3.org/2011/webtv/MPTF/cpreq.html)

These specs document earlier work with earlier dates and include references to W3C copyrights and Patent Policy. I don't want the earlier work to be forgotten because it's not linked by the final WG specs. I also want to acknowledge the Web & TV IG contribution to EME & MSE by way of producing these specs.

Perhaps EME & MSE could have brief History sections like the [History section of the HTML5 spec](https://www.w3.org/TR/html5/introduction.html#history-0). (Note: EME & MSE participants may know of other earlier documents that should also be referenced.)

PS: EME versions 0.1, 0.1a & 0.1b did indeed include a link to the Web & TV IG and a link to the Media Pipeline Task Force work in [Section 8.1](https://dvcs.w3.org/hg/html-media/raw-file/eme-v0.1b/encrypted-media/encrypted-media.html#faq-use-cases) under _Is this proposal compatible with adaptive streaming?_

**Comment by paulbrucecotton** [comment]
@ashimura and @mavgit - After determining that other W3C specifications normally only acknowledge WG participants and those in the public that were DIRECTLY involved in the specification work in their Acknowledgement sections, the HME WG Chair and Editors have decided  to follow this practice.
This means that we will NOT be adding the list of Web & TV IG members you provided to the EME or MSE Acknowledgement sections.  

@mavgit: In addition we will NOT be adding an informative reference to the two MPTF specs or adding a "history of EME/MSE" section to either specification.

@jdsmith3000 - Please revert the changes you made to the MSE Acknowledgments [w3c/media-source#48](https://github.com/w3c/media-source/issues/48) and finalize both this issue and the MSE issue based on the above guidance.

/paulc
HME WG Chair

**Comment by jdsmith3000** [comment]
Reverted previous commit for Acknowledgements.  I will create a PR soon to add this section back with updated names.
