### ISSUE TITLE
Can EME support link protection, such as DTCP-IP?

### ISSUE THREAD

**Issue by mavgit** [w3c/encrypted-media#118]
Link protection, such as DTCP-IP, is used widely and required by several specifications for delivery of video in the home network. Link protection can pass any format of video. Unlike other content protection systems, link protection negotiates a protected path between two endpoints, so it would never request a key from the application.

It seems that a link protection system like DTCP-IP could be treated like any other key system, but it would never request a key from the application. The benefit of using EME is that EME allows the media format and the content protection technology to be specified separately. 

So, can DTCP-IP, for example, be supported by the current EME API or would changes be required?

**Comment by mwatson2** [comment]
Link protection intersects with EME when it is used as Output Protection: that is media is delivered to a device using a keysystem and the keysystem license contains instructions as to Output Protection requirements for output of media from the device. Licenses are keysystem-specific, so keysystems can certainly include DTCP-IP in their supported output protection systems.

I'm not sure there is another way that link protection would intersect with DTCP-IP: if there is no need for interaction between keysystem server and a client side components then what do you need from the EME API ?

**Comment by mavgit** [comment]
@mwatson2 
> Link protection intersects with EME when it is used as Output Protection: that is media is delivered to a > device using a keysystem and the keysystem license contains instructions as to Output Protection 
> requirements for output of media from the device. Licenses are keysystem-specific, so keysystems can 
> certainly include DTCP-IP in their supported output protection systems.

I agree that this is how link protection intersects with EME *at the link protection source.*

> I'm not sure there is another way that link protection would intersect with DTCP-IP
(Presumably you meant "...intersect with EME")

The use case is on the other end of the link protection - on the receiving side.

If you have a DTCP-IP server (such as a video operator's in-home device) and a DTCP-IP client (such as a TV) and the client is running an HTML5 browser, how does the Web application running on the client web browser determine that the underlying client user agent can display DTCP-IP protected content?

> if there is no need for interaction between keysystem server and a client side components then what do 
> you need from the EME API ?

Usage of EME allows the client application to determine separately both the client support for DTCP-IP (as it does for other key systems) and the client support for a specific media type.

I think we can agree that the likelihood of having an additional W3C content protection API for supporting only link protection content protection is extremely unlikely.

**Comment by mwatson2** [comment]
For the case of a DTCP-IP sink device, the first question is how the DTCP-IP media is identified to the Media Element: is there a special URL format, specific MIME type ?

IIUC, DTCP-IP is not just a media format but an end-to-end protocol including a key exchange of its own (in-band with the media). So, one might expect a different URL scheme and / or MIME type.

EME capability detection handles the case where device capability for protected content might be different from that for non-protected support of the *same media type*. We need to know how DTCP-IP content is identified in order to determine whether and how it might integrate with EME capability detection.

**Comment by allanonz** [comment]
I've been working with DTCP-IP for a while now.   I can maybe answer some of the questions that seem to have come up in this thread.  DTCP-IP appendix specifies, and I believe that DLNA has also adopted the following.

DTCP V1SE 12.1 Recommended MIME type for DTCP protected content is defined as:
*  application/x-dtcp1;DTCP1HOST=\<host\>;DTCP1PORT=\<port\>;CONTENTFORMAT=\<mimetype\>
* CONTENTFORMAT is the content format of the media type protected by DTCP
* DTCP1HOST specifies the IP address of the DTCP Socket
* DTCP1PORT specifies the port number of the DTCP Socket

My reading of how EME interacts with a CDM seemed to me to indicate that this would be something that could work if, as I believe it's meant to be, the CDM and the License Server can have some back and forth that isn't limited to a single "message/update" cycle from the MediaKeySession.   That said I am currently investigating EME, and I am not a javascript/HTML application programmer, so I may be misinterpreting http://www.w3.org/TR/encrypted-media/

**Comment by mavgit** [comment]
I have confirmed with other DTCP experts that @allanonz is correct that DTCP V1SE 12.1 is the recommendation for the DTCP MIME type.

http://www.dtcp.com/documents/dtcp/info-20130605-dtcp-v1se-ip-rev-1-4-ed3.pdf
See page 48.

This should close my open action item.

**Comment by mavgit** [comment]
> @ddorwin added **feature request** **question** labels on Oct 30

FYI, as the one who opened this issue, I agree that it's a question, but I'm not making a feature request.

The original question:
> Can DTCP-IP, for example, be supported by the current EME API or would changes be required?

Sufficient answers for me would be either:
* Yes
* No with an explanation of which part of the spec disallows support.

If yes, I assume additional spec work would need to be done, such as a new stream format spec.

**Comment by paulbrucecotton** [comment]
>Sufficient answers for me would be either:
>    •Yes
>    •No with an explanation of which part of the spec disallows support.

@ddorwin and @mwatson2 - Do we have enough data to provide the requested answer?  If not what additional data might we need from @mavgit or @allanonz ?

**Comment by jdsmith3000** [comment]
I doubt we'd say a definitive "no", but it seems likely we'd need spec changes, since this is a new use case (and hence, marked "feature request") by @ddorwin.

The scenario has a home server serving up a webpage and sending DTCP-IP protected content to a browser based television client.  The MIME connection information isn't supported by EME, but the app might work around that.  If the client User Agent can detect the DTCP-IP content, and process messages to obtain keys, then there is at least some potential it could be decrypted and played.  Protecting key exchanges would be up the DTCP-IP CDM.

This would of course require new browser implementation work.

**Comment by mwatson2** [comment]
I feel this is a new feature request.

Of course, since we have opaque message passing to an opaque component, then the creator of the browser and the opaque component can choose to support anything they want. To give an extreme example (to illustrate the point), the mythical "Caffienium" browser supports a "Coffee Dispensing Module" which, when passed initData containing the IP address of an accompanying coffee machine, and a MIME type of a coffee drink, triggers said machine to make said drink. The MIME type application/x-expresso;strength=<x> is hereby defined.

What this is supposed to illustrate is that there are intended to be constraints on this API that are not technical or specified, but which we simply agree amongst us. For example, Caffienium does not really respect user privacy (the users preferred coffee strength is totally visible on the network) or security (the CDM has network access).

Put another way, if the question is whether the EME API could somehow be used to support DTCP-IP, then the answer is yes, just as it is for the Distributed Tepid Coffee Protocol (with apologies). If, on the other hand, the request is whether DTCP-IP can be supported by EME in a way which works within the EME architectural, security and privacy constraints, that needs a lot more discussion. I would say the latter is the feature request.

**Comment by mavgit** [comment]
Based on @jdsmith3000 and @mwatson2 replies, I conclude that there are no obvious API blockers against EME supporting DCT-IP, but verifying actual support would require significant additional work beyond the scope of this question.

Therefore, please close this issue, since my question was answered. This was helpful.

Please also remove both the **feature request** label and the **VNext** milestone, because I am _not_ asking for this feature to be added to this or the next version and don't want it recorded that I did. I was just asking a question that has now been answered. If someone else wants to request this feature, they can do so with a new issue. Thank you!

**Comment by jdsmith3000** [comment]
I've left this marked as a question, and cleared the other triage label/milestone settings.
