### ISSUE TITLE
Gracefully handling implementations that do not support setServerCertificate()

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#145]
As noted in the algorithm, Key Systems and specific CDM implementations may not support server certificates or providing them via [`setServerCertificate()`](https://w3c.github.io/encrypted-media/#setServerCertificate). For such implementations, the spec says to reject the promise with `NotSupportedError`.

An application that uses this method but does not explicitly handle `NotSupportedError` could unnecessarily fail when run on such implementations.

One option is to add a Note explicitly noting that applications should gracefully handle a rejection with `NotSupportedError` (while still seeing other rejections as unexpected failures). However, that seems like a strange requirement to place on applications when not supporting this method is allowed _and_ this "failure" does not negatively affect the rest of the application. (In other words, there is no exceptional behavior that needs to be executed.)

Alternatively, we could change the algorithm to resolve (while indicating that that the call did not actually do anything). This seems more consistent with https://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional. (This was the same principle that resulted in [`load()`](https://w3c.github.io/encrypted-media/#load) of an unrecognized session resolving with `false`.

Therefore, I propose changing `setServerCertificate()` to return a `Promise<boolean>` where the Boolean is `true` on success (current step 6) and `false` when the CDM does not support the operation (current step 2).

**Comment by joeyparrish** [comment]
I agree with this change.  It's easy for app developers to build Promise chains of several operations and treat any one rejected Promise as a failure for the whole setup chain.  Having setServerCertificate() return `Promise.resolve(false)` would be ideal, and backward-compatible with the current `Promise.<undefined>`.

One note, though, is that the format of server certs is CDM-specific, so an app already can't provide one single cert generically to all key systems.  Because of that, I can't imagine how I would end up giving a server cert to a CDM that doesn't support them.  Where would I have gotten it and what format would it be in?

**Comment by steelejoe** [comment]
@ddorwin - The proposed change makes sense. 

@joeyparrish - I agree, the spec is loose here on format. We should be able to address that by specifying a little more tightly e.g. a single DER-encoded X.509 certificate. The method name implies a single certificate, so the app should expect to call this method for each Key System that requires it. How the app gets the certificate is out of scope.

**Comment by ddorwin** [comment]
Thanks for the feedback, @joeyparrish!

In theory, one implementation of a Key System might not support them while others might. This may be especially relevant if a Key System vendor wanted to add support in the future.

One other theoretical possibility is that the application has a variable that is set based on the Key System selected and always calls `setServerCertificate()`, passing this variable.

That should work as long as all implementations correctly implement step 2 _and_ the value for key systems that don't support a certificate is **non-empty**. The latter is because step 1 checks for an empty value. Perhaps we should swap these steps so that we only check for an empty array when the method is actually supported. On the other hand, that could complicate implementations.

Speaking of implementations, Blink/Chromium currently implements step 2 within step 5, deferring that determination to the implementation rather than checking up front. This seems within the definitions for observable behavior except that the promise is rejected (will be resolved) asynchronously instead of synchronously as in the spec. is that difference observable? If so and this pattern is common, should we change the algorithm?

**Comment by steelejoe** [comment]
@ddorwin We currently do not support this call, but are very likely to in the future. Swapping the calls makes more sense to me and would answer the question about observable behavior in your case. I would like to get Chris Pearce's feedback though.

**Comment by ddorwin** [comment]
@cpearce, any comments on implementation?

Anyone know the answer to the observable difference issue?

**Comment by cpearce** [comment]
> I propose changing setServerCertificate() to return a Promise<boolean> where the Boolean is true on success (current step 6) and false when the CDM does not support the operation (current step 2).

I agree with this change, but I'd like to see the empty array check (step 1) and the check for whether the CDM supports server certs (step 2) swapped.

> @cpearce, any comments on implementation?

Firefox's MediaKeys.setServerCertificate implementation currently checks for an empty array and rejects the promise in its first step. We don't pass empty arrays to the CDM. Our implementation is not aware whether keysystems support setServerCertificate (though we could be), so we don't reject with NotSupportedError...

So for the proposed change to work for us, we'd need to change our implementation to be aware of whether setServerCertificate is supported, and we'd need step 1 and 2 swapped so that keysystems that don't yet support setServerCertificate are not disadvantaged. I think that's do-able.

**Comment by ddorwin** [comment]
I believe the summary is that there is agreement to a) make the originally proposed change and b) swap steps 1 and 2.

We will update Chrome's implementation to reflect this and address the issue I mentioned in January.
