### ISSUE TITLE
Should references to "media resource" be replaced by "media data"?

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#150]
There are currently seven occurrences of "media resource" in the EME spec.

According to [HTML5 definition](https://www.w3.org/TR/html5/embedded-content-0.html#media-data), "The term media resource is used to refer to the complete set of media data, e.g. the complete video file, or complete audio file."

Since EME treats audio and video separately (e.g. separate `MediaKeySystemMediaCapability` values) and is compatible with MSE [1], it seems we are rarely, if ever, referring to the complete set of media data.

@foolip, Do you agree with this interpretation?

[1] The MSE spec does not have any occurrences of "media resource" as it deals with unmuxed streams. @wolenetz.

**Comment by wolenetz** [comment]
MSE spec extends HTMLMediaElement algorithms that *do* deal with "media resource". MSE spec also allows for muxed stream data appends and parsing thereof by SourceBuffers (e.g. an audio+video+text muxed stream of data could be appended by an app to a single SourceBuffer in MSE). I defer to @foolip around the real question of what media resource really means in the context of EME at least.

**Comment by foolip** [comment]
These terms are rather high-level and don't really correspond to concrete concepts in an implementation. To a first approximation, I suppose "media resource" is simply the whole media file, and the spec talks about "the address of the media resource." Since it's also said to have tracks, a duration and other metadata, it's a bit like everything represented by Chromium's `WebMediaPlayer` interface.

The "media data" term is less concrete still, in some places it's used as if it means "bytes" as with the progress events. But it's also sometimes used to refer to specific type, as in "audio data" and "video data".

I would expect that MSE and EME would deal mostly with things we could call "media data", but at least in the case of MediaKeySystemMediaCapability's contentType member, it looks like it's really about the resource as a whole.

**Comment by jdsmith3000** [comment]
The current EME spec uses "Media Resource" 6 times vs. "Media Data" 57 times.  The current usages look reasonable to me:

2.0 Definitions, Key ID:  

> However, there is no requirement that Initialization Data contain any or all key IDs used in the media data or **_media resource_**. 

3.3.1 Dictionary MediaKeySystemMediaCapability Members, contentType:

> The type of the **_media resource_**. Its value must be a valid MIME type [HTML5].

8.4 Supported Media:

> This section defines properties of content (**_media resources_**) supported by implementations of this specification.

8.4.2 Interoperably Encrypted:

>**_Media resources_**, including all tracks, must be encrypted and packaged per a container-specific "common encryption" specification that allows the content to be decrypted in a fully specified and compatible way when a key or keys are provided.

12.5 Stored License, EXAMPLE 9:

> // Called if the application does not have a stored sessionId for the **_media resource_**.
> // Called if the application has a stored sessionId for the **_media resource_**.

I recommend closing this issue with no change.  If there are specific media resource usage instances some believe should be changed, please let me know.

**Comment by ddorwin** [comment]
Thanks for looking into this. I agree.
