### ISSUE TITLE
Review close() and remove() logic and behavior for persistent-* sessions

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#16]
[Bug 27111](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27111) created a separate session type for persistent licenses (i.e. offline) and sessions supporting persistent proof of key release. This allows us to be more explicit about the interoperable behavior applications should expect. Specifically, when should "release" messages be fired and when should a session's record be deleted. Preferably, both types would be consistent, but I don't think this is the case ([current flow](https://www.w3.org/wiki/HTML/Media_Task_Force/EME_Use_Cases#Limited_Concurrent_Streams_via_Key_Release)).

We need to review the currently-specified behavior, decide on desired behavior for each session type, and specify it in the algorithms.

**Comment by ddorwin** [comment]
As mentioned in #18, we need to determine the correct behavior for the `keyStatuses` attribute when a session is "released", especially when a `"persistent-release-message"` session is loaded. Should `keyStatuses` be empty or contain all the keys with a new `"released"` status?

**Comment by steelejoe** [comment]
I don't see a need for the "released" status mentioned above. Since ultimately the server is the decider of when a key has been released, I think if we wanted to support this we would need some support for a "released" message from the server (e.g. an update() after the release()). This does not make sense to me, but maybe I am misunderstanding the intent. 

Also - I agree that we should be more clear on the difference between release() and close(). For example, an application can ask for a key to be "released" but whether a key release message is actually sent depends on factors that may be outside the control of the app (tab is closed, storage is cleared, license is not actually appropriate to release, etc.).

**Comment by mwatson2** [comment]
I'm not sure a "released" status is necessary either, but if we had it I would expect it to mean that a key release message exchange is still pending. So perhaps "released" would not be the best term, as it would not apply to keys that have been removed / released / deleted but for which no key release message exchange is pending.

**Comment by ddorwin** [comment]
The keys are released (destroyed) before when the key release message exchange starts, right? The CDM will still be aware of them (or at least the session that contained them and the proof of release message), but I think the keys have been released at this point. They certainly aren't "usable."

We could just remove the key IDs from the session (see #18). Otherwise, we'll need some status to differentiate from "usable", etc. We'll probably have more clarity once we've addressed the main part of this bug.

**Comment by ddorwin** [comment]
>For example, if the session is closed because the browser window is closed, the UA should at least be allowed to attempt to send the key release messages (recognizing that this is not always possible, depending on browser implementation).

I don't think there is anything to be said. Most importantly, the UA does not "send the key release messages" to the server - it relies on the application to do so when it receives an event, which is itself asynchronous.

In this specific case, the user agent should shut down the session and CDM instances. This should result in the CDM closing the sessions and, in theory, requesting that the close algorithm be run. The CDM might also request that the UA fire a "message" event at the application, which would need to send an asynchronous XHR to report it to the server. However, the application, execution environment, and process hosting them are all being torn down as a result of the action that caused this flow to be initiated in the first place. Thus, all requests to the user agent will likely be dropped.

**Comment by mwatson2** [comment]
On Tue, Feb 10, 2015 at 7:28 PM, ddorwin <notifications@github.com> wrote:

> For example, if the session is closed because the browser window is
> closed, the UA should at least be allowed to attempt to send the key
> release messages (recognizing that this is not always possible, depending
> on browser implementation).
>
> I don't think there is anything to be said. Most importantly, the UA does
> not "send the key release messages" to the server - it relies on the
> application to do so when it receives an event, which is itself
> asynchronous.
>
> In this specific case, the user agent should shut down the session and CDM
> instances. This should result in the CDM closing the sessions and, in
> theory, requesting that the close algorithm be run. The CDM might also
> request that the UA fire a "message" event at the application, which would
> need to send an asynchronous XHR to report it to the server. However, the
> application, execution environment, and process hosting them are all being
> torn down as a result of the action that caused this flow to be initiated
> in the first place. Thus, all requests to the user agent will likely be
> dropped.
>
​The "remove" method explicitly states that it "MAY" involve messaging, but
no such statement is included in the close method or close algorithm. We do
have an open issue (16)​ to better define the behavior for persisten-*
sessions, but this also is only mentioned in the remove and close methods
and not in the close algorithm.

The reasons you cite for the message or network request being dropped are
implementation-specific. Whilst I recognize that some implementations are
moving to more and more aggressive shutdown making it likely the message is
not delivered in this case one can also imagine implementations which
provide time for this message to be processed and sent, at least in some
cases.

…Mark

**Comment by jdsmith3000** [comment]
It has been my belief that session release must always be initiated by the app, and not by the UA (as in the example of the browser window being closed).  My understanding is that release will remove session keys, including ones that are persistent.  That should only happen when the app issues the release command.

Close doesn't dispose of keys, but does release session resources.  Either one would affect keystatus, since it only makes sense in the context of a current MediaKeySession.

**Comment by mwatson2** [comment]
So, what _should_ happen when the browser window closes, for keys that are
not allowed to exist outside a single browser session ? Surely they are
released ?

...Mark

Sent from my iPhone

On Mar 16, 2015, at 7:00 PM, jdsmith3000 <notifications@github.com> wrote:

It has been my belief that session release must always be initiated by the
app, and not by the UA (as in the example of the browser window being
closed). My understanding is that release will remove session keys,
including ones that are persistent. That should only happen when the app
issues the release command.

Close doesn't dispose of keys, but does release session resources. Either
one would affect keystatus, since it only makes sense in the context of a
current MediaKeySession.

—
Reply to this email directly or view it on GitHub
<https://github.com/w3c/encrypted-media/issues/16#issuecomment-82032305>.

**Comment by ddorwin** [comment]
The behavior for `"persistent-license"` sessions has been defined (see commit above). A non-normative description is available in the wiki: https://www.w3.org/wiki/HTML/Media_Task_Force/EME_Use_Cases#Persisted_License_.2F_Offline

`"persistent-release-message"`behavior remains undefined, but that type should be removed (issue #45).

**Comment by mwatson2** [comment]
Sent from my iPhone

On Mar 31, 2015, at 5:42 PM, ddorwin <notifications@github.com> wrote:

The behavior for "persistent-license" sessions has been defined (see commit
above). A non-normative description is available in the wiki:
https://www.w3.org/wiki/HTML/Media_Task_Force/EME_Use_Cases#Persisted_License_.2F_Offline

"persistent-release-message"behavior remains undefined, but that type
should be removed (issue #45
<https://github.com/w3c/encrypted-media/issues/45>).

We haven't agreed to remove it, so how can this issue be closed ?

...Mark

—
Reply to this email directly or view it on GitHub
<https://github.com/w3c/encrypted-media/issues/16#issuecomment-88294522>.

**Comment by ddorwin** [comment]
>We haven't agreed to remove it, so how can this issue be closed ?

If we instead decided to keep it and define it's behavior, we can open a new bug. Until then, we don't need two bugs for the same issue.

**Comment by mwatson2** [comment]
Sent from my iPhone

On Mar 31, 2015, at 6:47 PM, ddorwin <notifications@github.com> wrote:

We haven't agreed to remove it, so how can this issue be closed ?

If we instead decided to keep it and define it's behavior, we can open a
new bug. Until then, we don't need two bugs for the same issue.

It's never stopped us before :-)

Closing the issue suggests that the issue is, well, closed, which it is
not. It's not worth further discussion, but for future reference I think
it's important to ensure that what we say to the outside world in terms of
open and closed issues is accurate.

...Mark

—
Reply to this email directly or view it on GitHub
<https://github.com/w3c/encrypted-media/issues/16#issuecomment-88308934>.
