### ISSUE TITLE
Use Contiguous IDL for WebIDL definitions

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#170]
When loading [encrypted-media-respec.html](http://w3c.github.io/encrypted-media/encrypted-media-respec.html), the following console warning is emitted:
>Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl

It would be nice to switch to the new model and eliminate this warning.

**Comment by mwatson2** [comment]
Contiguous IDL does not support automatic creation of the method parameter tables that we are presently using. I am wondering if we need anything more than the Parameter / Description columns since the other columns (Type, Nullable, Optional) are duplicative of information in the WebIDL itself ?

**Comment by ddorwin** [comment]
I'm not so concerned about those other columns, but it seems odd that the tables have been eliminated, requiring spec authors to manually format tables or lists and ensure they don't forget any. It's probably worth asking about this (is this intentional? best practices?) in the ReSpec repo.

**Comment by mwatson2** [comment]
What I read [here](https://readable-email.org/list/public-script-coord/topic/deprecating-old-idl) is that the tables were considered harmful because of the redundancy. In fact for requestMediaKeySystemAccess there is no information in the table which is not already in the material above, so I basically just removed it.

**Comment by mwatson2** [comment]
On further investigation there are other features (enumeration descriptions, dictionary descriptions) that we use extensively. Dictionary descriptions looks like regular `<dl>` format, so that is probably not a problem, but enumeration descriptions have a table format which would be messy to code by hand.

The rationale seems to be that all descriptions should be imperative (in the procedures) not declarative, which is not something I fully subscribe to (notwithstanding it being now an article of faith).

Since the changes would be quite extensive, I'd like to leave this one until we have addressed the blocking issues. At least these changes probably shouldn't be attempted with a lot of other PRs outstanding.

**Comment by plehegar** [comment]
This is indeed a pretty substantial editorial to do, speaking as someone who did it for some of the webperf spec. I support leaving on the side for the moment and keep it in the category "nice to have if time allows".

**Comment by mwatson2** [comment]
So, it turns out that @dontcallmedom has a magical version of ReSpec which "converts" old school to contiguous IDL. I now have this working, but we need [iterable support in the contiguous IDL version](https://github.com/w3c/respec/pull/871) first.

**Comment by ddorwin** [comment]
@mwatson2, Your ReSpec PR has been merged, so you should be able to make a PR of the above commit.

**Comment by mwatson2** [comment]
Here is the Pull Request: #274. Could someone take a look before I merge.
