### ISSUE TITLE
Add event handler attributes (e.g. onkeystatuseschange on MediaKeySession)

### ISSUE THREAD

**Issue by foolip** [w3c/encrypted-media#176]
Justification is the same as in https://github.com/w3c/media-source/issues/66 and this issue should probably block on the resolution of that.

**Comment by ddorwin** [comment]
Based on https://github.com/w3ctag/design-principles/issues/29#issuecomment-215560292, we should have event handler attributes for all of our events.

We need to add attributes for both [`MediaKeySession` events](https://w3c.github.io/encrypted-media/#mediakeysession-events):
* `onkeystatuseschange`
* `onmessage`

Of the [`HTMLMediaElement` events](https://w3c.github.io/encrypted-media/#htmlmediaelement-events):
* We already have  `onencrypted`.
* We need to add `onwaitingforkey`.

**Comment by jdsmith3000** [comment]
This is a clearly defined change that is ready for implementation.

**Comment by foolip** [comment]
See https://github.com/w3c/html/issues/335#issuecomment-222329752 for a detail you'll need to decide on.

**Comment by ddorwin** [comment]
@foolip, does this only apply to the two `HTMLMediaElement` event handlers?

@domenic said, "So I guess if it bubbles it belongs there." Related to bubbling, the spec text currently says:
* "Queue a task to create an event named encrypted that **does not bubble*** and is not cancellable..."
* "Queue a task to **fire a simple event** named waitingforkey at the media element."
  - Per HTML5, "Firing a simple event named e means that a trusted event with the name e, which does not bubble (except where otherwise stated) and is not cancelable (except where otherwise stated)..."

Thus, it would seem there is no bubbling and thus no need to put these on the `GlobalEventHandlers`. However, HTML5 also uses the "fire a simple event" language for `play`, `playing`, and likely others, which seems inconsistent with @domenic's guidance.

**Comment by foolip** [comment]
Yeah, all events in HTML are on `GlobalEventHandlers` even if they don't bubble, for simplicity I suppose.

I would go with extending `HTMLMediaElement` only, since it's easier to move in the direction of `GlobalEventHandlers` than moving away from it.

**Comment by ddorwin** [comment]
@jdsmith3000, this is ready for implementation per the original plan.

**Comment by jdsmith3000** [comment]
The original plan included adding attributes for MediaKeySession  events:
• onkeystatuseschange 
• onmessage 

And HTMLMediaElement  events:
•Done already: onencrypted .
•Need: onwaitingforkey .

Please confirm that we now only need to add an attribute for onwaitingforkey to the HTMLMediaElement extensions.

I'm preparing this change now.

**Comment by ddorwin** [comment]
I don't believe anything has changed with respect to `MediaKeySession` and we should add those two event handler attributes as well. Yes, the only change to `HTMLMediaElement` is to add `onwaitingforkey`.

**Comment by ddorwin** [comment]
Fixed by 3d4a9ce.
