### ISSUE TITLE
"persistent-usage-record" sessions should not be handled in remove()

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#180]
For most ("happy case") `"persistent-usage-record"` sessions, it will be irrelevant whether usage data was persisted. (Conceptually, from the application's point of view, the record is only stored if it was not handled and cleared during the application’s lifetime.) Thus, applications may find it confusing to call `remove()` when they have not explicitly persisted something. Additionally, unlike `"persistent-license"` sessions, `remove()` never actually _removes_ anything for  `"persistent-usage-record"` sessions. (`update()` removes the relevant record for both types of sessions.)

Pulling `"persistent-usage-record"` out of the `remove()` algorithm will focus it on removing (destroying) persisted license(s) and keys(s). (Currently, this is applicable only to `"persistent-license"` sessions. In-memory keys are destroyed when a session is closed, so there is no reason to cover those in this method.) This would make resolving #155 much more straightforward.

<br/>Let’s take a look at what `remove()` currently does for `"persistent-usage-record"` sessions. Currently, it destroys the keys, persists the _record of key usage_, and generates a message.

As the discussion in Issue #171 and related PRs has helped highlight, there are multiple paths to closing sessions and the resulting actions of destroying ephemeral keys and storing the _record of key usage_ for `"persistent-usage-record"` sessions. This seems to make handling this session type in `remove()` redundant except for the queuing of a message. (The in-memory keys are destroyed and the _record of key usage_ is persisted in both cases.)

The session closing paths do not currently perform two operations:

1. Generating a release message when the session is closed.
1. Generating a message for a loaded session containing a persisted record of key usage.
 * This is for the "unhappy case" where the first message was not sent and/or ACK’d.
 * Note that in this case the keys are unnecessarily destroyed (there aren’t any) and the _record of key usage_ is re-stored.

Is there a reason (1) shouldn’t be performed by `close()` (or any other reason the session is closed)?

I see three ways that (2) could be handled. In order of preference:

* `close()` always generates a message for the _record of key usage_, which would have been loaded into the session by `load()`.
 - This seems the most consistent from an application point of view.
 - The loaded sessions is the same as an active session except there are no keys.
* `load()` generates the message, which is something the algorithm already allows.
 - We can add normative steps for this session type there
* `remove()` only generates messages in case (2).
 - This seems inconsistent and makes it hard to define the purpose of `remove()` (see #155).

Note: The loading of `"persistent-usage-record"` sessions and correct behavior of the `remove()` algorithm currently greatly depends on the definition of [Known Key](https://w3c.github.io/encrypted-media/#known-key) and understanding that a record of key usage was persisted. Even so, I’m not sure there is any language indicating the new session’s _record of key usage_ is actually populated with the stored data.

**Comment by ddorwin** [comment]
Yes, `remove()` would never be called for this session type.

>is it legal to call update() on a session for which you have already called close()?

Yes, though the path is subtle. Step 4.2.2 of the `close()` algorithm is:
 >If the preceding step caused the session to be closed, run the Session Close algorithm on this object.

One might imagine that the session is not actually "closed" until the Session Close algorithm is run in the `update()` algorithm. We should probably be more clear about this, at least in a Note.

For `"temporary"` and `"persistent-license"` sessions, the closing should happen fairly quickly* and neither `remove()` nor `update()` would be callable. (If an app wants to remove an active  `"persistent-license"` sessions, it should call `remove()`, not `close()`.)

* When exactly calling other methods is disallowed is a bit imprecise. See also item 7 in #181.

**Comment by mwatson2** [comment]
I had assumed that `close()` would close the session (despite that text). It would be nice (clearer) if it did.

Otherwise we are overloading the `close()` method: on the one hand to really close the session and on the other had just to delete the keys and send the message. However, currently we are overloading the `remove()` message: to remove persistent state and to remove temporary keys / licenses.

It's not onvious which overloading is more confusing.

For me, the most consistent approach is:
- `close()` always closes the session and nothing can happen on a closed session. If there is a _record of key usage_ it gets persisted but there is no message
- the CDM could destroy the keys and send a _record of key usage_ message for its own reasons any time (this would not close the session)
- `remove()` removes both persistent and temporary keys and licenses. If anything was removed, you get a message
- `load()` of a session containing only an unacknowledged _record of key usage_ or _record of license destruction_ causes the message to be generated.

**Comment by mwatson2** [comment]
Having made substantial progress on #181, I do not think there is an issue with the existing specification here.

We are clear that once a session is closed no further operations can be performed on it.

At some earlier point, the message containing the _record of key usage_ was generated on session close. This was deliberately changed after some discussion so that the explicit `remove()` call was necessary to generate that message. If a session is closed without calling remove, then whilst the _record of key usage_ is stored, there is no notification. I don't think there is any strong rationale to change that now, given that it would affect existing implementations.

So, I propose we close this without changes.

**Comment by steelejoe** [comment]
I agree. I don't think any more changes are needed now that we have agreed no actions happen on a closed session.

**Comment by mwatson2** [comment]
@mwatson2 and @jdsmith3000 discussed at editors' meeting: the proposed change doesn't seem to help with interoperability given that we have established procedures.

**Comment by mwatson2** [comment]
Our suggestion is to close without changes, given the V1 timeframes.

**Comment by mwatson2** [comment]
@ddorwin @mwatson2 and @jdsmith discussed this issue. Our proposal is to support `remove` for temporary sessions. This is based on the following:
- `remove` removes license and keys (whether persisted or not)
- `close` means the application is finished with the session, which has effect of removing all temporary (in memory) state, including keys etc.
- to retrieve the _record of license destruction_ or _record of key usage_ for a session from a previous browsing session, you just need to `load` that session and the message will be sent.

**Comment by mwatson2** [comment]
I will create a Pull Request, including the changes proposed for #155

**Comment by mwatson2** [comment]
Pull Request #208

**Comment by ddorwin** [comment]
This was fixed by https://github.com/w3c/encrypted-media/commit/4d5498e210e938f1c1d2fd4908bbeab2df7467be. Note that outcome was different than the summary - see the summary in https://github.com/w3c/encrypted-media/issues/180#issuecomment-222194463.
