### ISSUE TITLE
Registry SOTD

### ISSUE THREAD

**Issue by plehegar** [w3c/encrypted-media#183]
[[
From the Director's review: For the two registry Notes, I encourage an additional sentence or two in 
the SoTD stating any expectations the Group has concerning updating the 
registry.  See, for example, the example in the TTML Profile Registry.
]]

The TTML profile registry says:
[[
This is a registry and may be updated without any notices.
]]
https://w3c.github.io/tt-profile-registry/

**Comment by dret** [comment]
i think i am struggling a bit with this concept: the NOTE document *is* the registry and will be updated whenever the registry contents get updated? is there any kind of change tracking to understand *what* has changed and why and by whom? i would like to encourage the w3c to come up with a different model for operating registries, this looks like something that won't scale very well and will make it hard to track registry changes. https://tools.ietf.org/html/draft-wilde-registries is not quite finished but something i have been working on for a while. given that w3c has not the same baggage as IETF with their IANA setup there's a good chance to come up with something that works well across various specs needing registries. change tracking, machine-readable registry contents, and consistent submission procedures could be possible targets. at https://github.com/w3c/manifest/pull/458 i am trying to work on this for another w3c spec, and i think it would be great to not reinvent the wheel every single time a registry is needed (more registries are underway such as over here: https://www.w3.org/TR/payment-method-id/).

**Comment by paulbrucecotton** [comment]
The primary content in the EME registry is the mapping of the three current "Initialization Data Types" ie cenc, keyids, webm to the "Public Specifications" that describe these types.  The MOST common change that would occur here is the addition of a new row to the table in Section 4 of
http://www.w3.org/TR/eme-initdata-registry/#registry

The same kind of content is found in the MSE registry which maps "byte stream formats" to "Public Specifications":
https://w3c.github.io/media-source/byte-stream-format-registry.html 

I am not convinced that your comments about "won't scale very well" or "hard to track registry changes" really apply to these EME or MSE registries.

**Comment by jdsmith3000** [comment]
I think it's very reasonable to add a statement like this to the registry index.html documents:

> This is a registry and may be updated without any notices.

If there are no objections, I will go ahead and make that change.

**Comment by dret** [comment]
On 2016-05-10 12:45, jdsmith3000 wrote:
> I think it's very reasonable to add a statement like this to the
> registry index.html documents:
>
>     This is a registry and may be updated without any notices.
>
> If there are no objections, I will go ahead and make that change.

better than nothing, but it still seems odd to see the registry contents 
being embedded in the registry spec, with no access to the contents per 
se in machine-readable format. there's no need for anything fancy at 
all, but at least something that can be easily parsed such as CSV, XML, 
or JSON.

also, isn't it incorrect that the "registry ... may be updated without 
any notices"? i'd assume an updated NOTE to be pushed to the TR stream, 
or would the existing NOTE just silently change? not that this would be 
a great way to see registry updates, but you would see them, right?

**Comment by paulbrucecotton** [comment]
>it still seems odd to see the registry contents being embedded in the registry spec, with no access to the contents per se in machine-readable format. 
@dret - Can you explain why someone would want a machine readable EME or MSE registry?  See also my earlier comment above.

**Comment by paulbrucecotton** [comment]
@plehegar - Since the registries has been [published](https://www.w3.org/blog/news/archives/5392) without the recommended text: "This is a registry and may be updated without any notices.", when do you propose to add this text?  I recommend that this issue be marked with the V1NonBlocking milestone.

**Comment by dret** [comment]
On 2016-05-10 11:53, Paul Cotton wrote:
> The primary content in the EME registry is the mapping of the three
> current "Initialization Data Types" ie cenc, keyids, webm to the "Public
> Specifications" that describe these types. The MOST common change that
> would occur here is the addition of a new row to the table in Section 4 of
> http://www.w3.org/TR/eme-initdata-registry/#registry
>
> The same kind of content is found in the MSE registry which maps "byte
> stream formats" to "Public Specifications":
> https://w3c.github.io/media-source/byte-stream-format-registry.html
>
> I am not convinced that your comments about "won't scale very well" or
> "hard to track registry changes" really apply to these EME or MSE
> registries.

fair enough. and my apologies for the belated response. i guess i am 
coming mostly from a general "how does the @w3c handle registries" 
angle, because of the recent uptick in those being created, for example 
for TTML, EME, web manifest, and web payments. so far, everybody is 
rolling their own, and not necessarily looking at all the questions that 
should be considered when establishing and managing a registry.

so maybe my concerns don't really apply all that well to this particular 
one (it's hard to tell the envisioned registry evolution from just 
looking at the initial spec and state). i would still like to encourage 
the authors/editors to have a look at 
https://tools.ietf.org/html/draft-wilde-registries and use it as a brief 
checklist of whether they have at least considered (and maybe decided to 
ignore) all the issues listed there.

**Comment by ddorwin** [comment]
What is the status of this?

The original proposed change seemed straightforward and at least clarified the current expectation/process. @plehegar, does this only apply to the registry indexes and not the individual entries?

@dret, are there specific changes you would like to see from the IETF draft? Since I'm guessing this would involve larger changes, it probably makes sense to file a separate issue to consider and discuss this topic.

I propose that @jdsmith3000 makes the originally proposed change per his earlier offer so that @plehegar can pick that up when he republishes the registries to fix #317.

**Comment by dret** [comment]
not quite sure what you mean by this, @ddorwin: "are there specific changes you would like to see from the IETF draft?"
what i am trying to say is that if it is a registry, maybe manage it as a registry. that's also what that draft is saying: registries exist because they are structured, can easily change, and are used for lookup; that's slightly different from what spec publishing is about.
i am currently working on an open and github-based tool that should allow to manage any number of registries easily, so that registry updates are easy, can be tracked and archived, and there is a simple workflow for publication, updates, and retrieval.
i'd be more than happy to try to use the two (?) encrypted media registries as experiments and examples, because as usual, it's great to have a real world use case.

**Comment by dret** [comment]
fwiw: the same problem exists over at web manifests. they solve the problem differently but also have to solve it, because w3c provides no support for spec-writers for managing registries.

**Comment by ddorwin** [comment]
@dret, it sounds like you're proposing a W3C process change to better or explicitly support registries rather than something specific to the EME registries. Is that correct? Has this topic been raised with the AB?

**Comment by dret** [comment]
@ddorwin yes, i see this as a pattern occurring across some @w3c specs and i think when you look at IETF, it is not unlikely that this is just a start and may need a bit more planning than just putting out a bunch of NOTEs and updating them. i understand that @w3c currently simply doesn't actually support anything like this, and my hope is that this might change. i think that would be good foresight and planning. but just to repeat myself: given the lack of support right now, maybe this NOTE path is the only viable way.

**Comment by plehegar** [comment]
@dret, I'd be curious to know if you have a proposal on how W3C could support registries in general. I don't mind W3C having one, it's just that it isn't on the top of my list at the moment.

**Comment by dret** [comment]
On 2016-09-12 14:21, Philippe Le Hegaret wrote:
> @dret <https://github.com/dret>, I'd be curious to know if you have a
> proposal on how W3C could support registries in general. I don't mind
> W3C having one, it's just that it isn't on the top of my list at the moment.

looking at how IETF/IANA does it is a very good starting point. it might 
also be a good starting point for thinking about what to do differently. 
but the general idea of having something like RFC 7500 as the starting 
point will help.

personally, i am working on creating something that should work a little 
bit smoother than IANA, but that's work in progress. i'd be happy to 
chat about it, and even happier if that would result in some feedback 
for my project.

in the end, the beauty of registries is that it's not a technologically 
complex problem. it just needs awareness of the general pattern and its 
utility (https://tools.ietf.org/html/draft-wilde-registries), figuring 
out policies around it, and then providing a platform that supports 
those policies and can be easily used by spec developers.

**Comment by ddorwin** [comment]
This might be good W3C TPAC Plenary Day session topic

**Comment by dret** [comment]
On 2016-09-12 15:16, ddorwin wrote:
> This might be good W3C TPAC Plenary Day session topic

i would very much think so. the fact that IETF/IANA has ~1600 registries 
in place may tell you a little bit about the fact that the general 
pattern is not some exotic edge case.

**Comment by plehegar** [comment]
TPAC plenary session seems a good idea indeed. adding @wseltzer and @swickr who are interested in the topic.

**Comment by ddorwin** [comment]
@plehegar, what is the plan to address the original issue?

**Comment by plehegar** [comment]
@dret is working on a proposal for registries at W3C. We should probably track that somewhere and reopen a new issue once W3C has a better alternative. @dret, do you concur?

**Comment by dret** [comment]
sounds good. https://github.com/dret/RegMan is my project which is currently empty. but the registry stuff now has bubbled up near the top of my priority list, and my goal is to start working on this very soon. 
https://github.com/dret/RegMan/blob/master/W3C.md is the only interesting file in there right now; it's a collection of ongoing W3C activities that maybe would benefit from being managed as registries. this issue/spec is listed already.

**Comment by plehegar** [comment]
closing under there is some concrete ideas of what to do here.
