### ISSUE TITLE
Editorial: There is no definition for "unclosed session"

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#185]
This was originally noted in https://github.com/w3c/encrypted-media/pull/184#discussion-diff-62884149.

We use "unclosed session" three times in (normative parts of) the spec, but this term is not defined. In most `MediaKeySession` algorithms, we use language similar to  `the <a def-id="session-closed-algorithm"></a> algorithm has been run on this object`.

We should do one of the following:

1. Replace the "unclosed session" instances with such text.
1. Add a definition for "closed session", possibly using such text, and update all such text as well as these three cases to reference the definition.

(2) might be better from a readability perspective and avoids having to ensure we get the somewhat complex text correct everywhere.

**Comment by mwatson2** [comment]
I think we will need separate definitions for closed session and closed MediaKeySession. The latter implies the former, but not the other way around, first because the session is closed just before the MediaKeySession in the normal case and second because MediaKeySession can be destroyed without being closed, but the session is still closed in this case.

Why don't we address this in the #184 ?

**Comment by mwatson2** [comment]
PR #255
