### ISSUE TITLE
the EME WG is ignoring "inconvenient" issues

### ISSUE THREAD

**Issue by GravisZro** [w3c/encrypted-media#188]
Members of the EME WG are wilfully ignoring issues that must be addressed ensure platform compatibility (#166/#159) and refuses to remove ensnaring legal language (#157).  I have suggested many solutions that would work for all but a select subset of businesses using DRM.  However, instead of selecting the obvious solutions that would benefit the general public, the EME WG has chosen to ignore these issues because doing so would disrupt their various corporation's plans for [hardware lock-ins](http://www.extremetech.com/extreme/204319-windows-10s-playready-3-0-mandates-hardware-drm-for-4k-playback), [DRM licensing schemes](https://www.microsoft.com/playready/licensing/) and legal snares.

**What this all boils down too is that only one group of people will be able to view 100% of sites using commercial CDMs: people who bought a Windows 10 computer in the last year _and_ use Chrome, Firefox or Edge.**

This means if your CPU is from 2014, you can't view 4K content.  If you are on Windows 7/8.x or Apple OS X you can't view 4K content even if it's a 4K SmartTV!

**People who can view 0% of sites using commercial CDMs:**
* anyone with a browser that is not Chrome/Firefox/Edge/Safari
* FreeBSD users
* everyone using PowerPC (e.g. OSX and the upcoming libre [Talos Workstation](https://www.raptorengineering.com/TALOS/prerelease.php))
* non-x86 Linux users (except Android on ARM)
* **ALL OTHER OPERATING SYSTEMS AND ARCHITECTURES**

Without any members of the EME WG willing to address issues in an honest and open manner to ensure that the EME and CDMs comply with the [Design Principles of the W3C](https://www.w3.org/Consortium/mission#principles) of a _Web for All_ and _Web on Everything_, **the EME WG should be dissolved** because it is composed of members that are incapable of being impartial due to _direct_ conflicts of interest.

**Comment by GravisZro** [comment]
CC: @marcoscaceres @martinthomson @mattgarrish @michael-n-cooper @mikewest @mounirlamouri @nandana @newtoncalegari @omo @othermaciej @patrickhlauke @pkra @plehegar @plinss @rdeltour @rhauck @richtr @rubys @scottgonzalez @shigeya @sideshowbarker @silviapfeiffer @sitkevij @snsk @steverep @tabatkins @techtoons @tguild @tobie @toddreifsteck @travisleithead @tripu @upsuper @Velmont @vivienlacourba @wikier @wilhelm @wseltzer @yakovsh @yatil @ylafon @zcorpan @zqzhang @zsoltpardi

**Comment by phuslu** [comment]
![2016-05-13_205015](https://cloud.githubusercontent.com/assets/195836/15248340/470d162a-194c-11e6-81a7-188ac81ba57b.png)

Hi dude, *Someone* appraise your post(CC many people then edit to hide) is trolling.

**Comment by paulbrucecotton** [comment]
The HME WG participants and Editors are working within the scope of the current HTML Media Extensions WG [charter](http://www.w3.org/2013/09/html-charter.html) and to the recently published [timeline](https://lists.w3.org/Archives/Public/public-html-media/2016May/0029.html).  As such many of the features you are requesting are simply "out of scope" of the current charter and cannot be delivered as part of EME 1.0. 

Therefore we are marking several of your requests with the Milestone VNext so that they can be considered when the HME WG is re-chartered after we have completed EME 1.0.

Since this issue does not request any specific changes to the EME specification on its own, we will close this issue.

You can file a [formal objection](http://www.w3.org/2005/10/Process-20051014/policies.html#FormalObjection) to this decision by sending an email to public-html-media@w3.org citing your technical arguments and proposed changes that would remove your Formal Objection.

/paulc
HTML Media Extensions WG Chair

**Comment by ddorwin** [comment]
Closing per the previous comment.
