### ISSUE TITLE
Ensure promises returned by methods are fulfilled before event handlers are executed

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#19]
[This issue is broken out from the second comment in #14.]

The intended behavior, at least for `generateRequest()` and `load()` is that the promise will be resolved (`.then()` statements run) before events handlers for events fired by the algorithm run. This is what authors are likely to expect. As an example, an author might want to do something - possibly related to the new `sessionId` - when the `generateRequest()` promise is resolved and ensure that this happens _before_ the `message` event handler runs. The current spec text makes no such guarantee. This issue tracks ensuring the intended order.

This issue takes priority over and thus blocks #14.

**Comment by cpearce** [comment]
In the Firefox/Adobe case, on the first time generateRequest() is called the CDM may need to send one or more "individualization-request" messages before the CDM can send an actual "license-request" message to the JS App.

So we may need to send multiple messages and expect responses returned via update() calls before the promise by generateRequest() can be resolved.

So its not going to work for us to specify here that *no* events can be fired at the MediaKeySession before the promise returned by generateRequest() is resolved.

Specifying that only "individualization-request" MediaKeyMessageEvents can be sent before the promises are resolved might work, but I'd want someone from Adobe to agree to that first.

**Comment by ddorwin** [comment]
The generate license request algorithm was always intended to support multiple messages/round trips. This could be part of the protocol or for other things, such as to obtain a server certificate when one has not been provided otherwise. I see that the algorithm (now `generateRequest()`) has evolved to require the first message be a license request generated from the initData. I filed #31 to fix that. We still need to ensure that events are not fired until after the promise is resolved, which is the topic of this bug.

**Comment by cpearce** [comment]
I am fine with specifying that events are not fired until after the promise is resolved.

**Comment by jdsmith3000** [comment]
Perhaps we should look at having the promise directly return with message data.  Right now, these methods are constructed as promises and mostly return voids.  We then using a second callback method via events to pass message data.  Are there reasons not to have the promise handle this callback entirely?

    Promise<void>    generateRequest (DOMString initDataType, BufferSource initData);
    Promise<boolean> load (DOMString sessionId);
    Promise<void>    update (BufferSource response);
    Promise<void>    close ();
    Promise<void>    remove ();

**Comment by joeyparrish** [comment]
Since renewal messages are delivered via event, having initial requests delivered via event as well is simpler, IMHO, for app/library developers.  I write one handler that dispatches messages to the license server, regardless of whether it was initiated by generateRequest or not.

**Comment by jdsmith3000** [comment]
I'm okay with specifying that events are not fired until after the promise is resolved.

**Comment by paulbrucecotton** [comment]
The Sapporo F2F meeting assigned ACTION-106 to @ddorwin 
http://www.w3.org/2015/10/30-html-media-minutes.html#item22

ACTION-106: Propose soluiton for issue-19
https://www.w3.org/html/wg/media/track/actions/106

**Comment by domenic** [comment]
@ddorwin asked me to look this over and give some concrete advice.

One thing to note that has changed since the original issue is that https://github.com/w3ctag/promises-guide/issues/47 led to "resolve a promise" to be defined to queue a task (if the algorithm is running in parallel). This helps make things a decent bit clearer and simpler, in fact. My previous mental model for "resolve a promise" was making things more complicated than they should be.

So with that in mind, to get the desired behavior, generateRequest and load just need to swap their appropriate steps, e.g. swap step 12 and 13 in generateRequest.

----

Why this works:

Assume the task queue is completely empty, and we are running "in parallel" (i.e. in some other thread).

- New step 12 queues a task to resolve _promise_ (by the definition of "resolve a promise" which automatically does that for you).
- New step 13 queues a task to fire the event.
- "In parallel" section of algorithm is over. That thread spins down, or whatever.
- Back in the main thread, the [event loop](https://html.spec.whatwg.org/#processing-model-8) notices it has some tasks. It processes them in FIFO order:
  - Ah, a task to resolve _promise_. Let me run that (event loop step 3).
  - _promise_ is now fulfilled. This causes [the relevant ECMAScript machinery](https://html.spec.whatwg.org/#enqueuejob(queuename,-job,-arguments)) to queue a microtask to run any fulfillment handlers.
  - Task is done running. At event loop step 6, we perform a microtask checkpoint. This will call the fulfillment handlers! Yay!
  - Event loop eventually loops back around and runs the task to fire the event. This synchronously calls any event listeners. But the promise fulfillment handlers have already run, so we're good!

**Comment by ddorwin** [comment]
Thank you @domenic! This seems pretty straightforward for implementation.

@domenic, is there any update on getting some of these shorthands and definitions into Web IDL or somewhere else we can link to? For now, should we duplicate them somewhere in our spec?

**Comment by ddorwin** [comment]
This is blocking some other issues, so we should implement it soon.

**Comment by domenic** [comment]
> @domenic, is there any update on getting some of these shorthands and definitions into Web IDL or somewhere else we can link to? For now, should we duplicate them somewhere in our spec?

You can just link to https://www.w3.org/2001/tag/doc/promises-guide, I believe.

**Comment by ddorwin** [comment]
@plehegar, are there any issues with normative links/references to https://www.w3.org/2001/tag/doc/promises-guide?

**Comment by jdsmith3000** [comment]
We agreed to prioritize closing this issue.  The planned fix is to:

- Swap the promise resolution and queue event tasks in `load()`and `generateRequest()` so that the promise resolution is queued before events.  This sets the desired order of execution based on current promise handling guidelines.
- Remove Issues 6 and 7 from the spec (based on this fix).
- Reference [Writing Promise-Using Specifications, Manipulating Promises](https://www.w3.org/2001/tag/doc/promises-guide#shorthand-manipulating) for the guidance that makes this fix possible.

@plehegar, is this normative reference acceptable?

**Comment by jdsmith3000** [comment]
I've found normative references to https://www.w3.org/2001/tag/doc/promises-guide in other W3C specs:

- [Service Workers Nightly](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/) 
- [Presentation API](https://w3c.github.io/presentation-api/)

The Presentation API refers to the spec as a "finding" and the Service Workers Nightly refers to it as a "finding of the W3C TAG".  I suggest if we use it, that we follow the Service Worker example and update the date:

> [PROMISES-GUIDE] 
> 
> Writing Promise-Using Specifications. 16 February 2016. Finding of the W3C TAG. URL: https://www.w3.org/2001/tag/doc/promises-guide

**Comment by paulbrucecotton** [comment]
I don't believe we need to add a reference the [PROMISES-GUIDE] to the EME spec if its only use is to provide a rationale for the design of our API.  Having this information in this GitHub issues is all we need to do.

**Comment by ddorwin** [comment]
I believe we want to reference the Guide via links to terms we (intend to) use that defined in it. My understanding of https://github.com/w3c/encrypted-media/issues/19#issuecomment-188497121 is that the Guide contains algorithmically-relevant descriptions for the shorthands we intend to use.

Specifically, we want to use and refer to https://www.w3.org/2001/tag/doc/promises-guide#resolve-promise and maybe https://www.w3.org/2001/tag/doc/promises-guide#reject-promise.

**Comment by paulbrucecotton** [comment]
Referring to explicit parts of the Guide makes sense.  Thanks for the rationale for the reference.

**Comment by jdsmith3000** [comment]
I specifically want to reference the queue for resolving promises that ensures proper timing between the promise completion and events:

> If the algorithm using these shorthands is running in parallel, the shorthands queue a task on p’s relevant settings object’s responsible event loop to call the stored function.

Since this reference affects at least two algorithm steps, I might do this with a note after the two steps.

**Comment by jdsmith3000** [comment]
As an alternative, we might note the expectation that promise resolutions are queued in the event loop without specifically referencing the guidance.  It's not as clear, but perhaps sufficient.

**Comment by jdsmith3000** [comment]
Paul has asked me to proceed with this edit and reference the promises guide.  `[[PROMISES-GUIDE]]` is already globally defined and creates an informative reference.  I believe this is sufficient and will use it in my change.

> [PROMISES-GUIDE]
> Domenic Denicola. W3C. Writing Promise-Using Specifications. 16 February 2016. Finding of the W3C TAG. URL: https://www.w3.org/2001/tag/doc/promises-guide

**Comment by jdsmith3000** [comment]
Implemented fix.  I noted that all of the guidance in the PROMISES-GUIDE is concerned normative (unless otherwise noted).
