### ISSUE TITLE
Note "at risk" features in the specification before CR transition

### ISSUE THREAD

**Issue by mwatson2** [w3c/encrypted-media#206]

**Comment by paulbrucecotton** [comment]
The HME WG recently [approved](https://lists.w3.org/Archives/Public/public-html-media/2016May/0060.html) the addition of the "secure release" feature to the list of "at risk" features in the upcoming EME Candidate Recommendation publication.

**Comment by ddorwin** [comment]
When referencing the "secure release" feature, we should use "[`persistent-usage-record`](https://w3c.github.io/encrypted-media/#idl-def-MediaKeySessionType.persistent-usage-record)," which is how it is known in the spec.

We also [discussed](https://github.com/w3c/encrypted-media/issues/129#issuecomment-222017627) marking 'the feature of "modifying `readyState` based on key availability" as "at risk".'

**Comment by paulbrucecotton** [comment]
>We also discussed marking 'the feature of "modifying readyState based on key availability" as "at risk".'

If the Editors want to recommend this feature be added to the EME "at risk" list of features they should send an appeal to the [WG Decision](https://lists.w3.org/Archives/Public/public-html-media/2016May/0060.html) IMMEDIATELY so that we can process the request BEFORE June 9.

/paulc

**Comment by ddorwin** [comment]
My understanding of the WG Decision is that it was to add a specific feature to the list, not that this would be the _only_ feature. Thus, I don't think an appeal of that Decision is necessary.

A question about the process: Is a CfC for each proposed at risk item required prior to publishing the CR?

Regardless, we should start adding at risk items to the spec text because they will need to be included in the CR to be published on June 16th.

**Comment by paulbrucecotton** [comment]
>A question about the process: Is a CfC for each proposed at risk item required prior to publishing the CR?

A separate WG CfC is not required but is probably preferred since if there are objections to designating one feature as being "at risk" in a WG CfC that attempts to add multiple features as being "at risk", it make my role as Chair harder since I have to figure out what "consensus" is. 

Do the Editors want me to start a WG CfC to add 'the feature of "modifying readyState based on key availability" as an EME "at risk" feature?

>Regardless, we should start adding at risk items to the spec text because they will need to be included in the CR to be published on June 16th.

FTR, the "at risk" items are identified in the Status section of the document.  Please feel free to update the SOTD section with any "at risk" items the WG has agreed to.

As per our [timeline](https://lists.w3.org/Archives/Public/public-html-media/2016May/0029.html), we will publish a new EME WD on June 9 and use that as the basis for a WG CfC to go to Candidate Recommendation.  Since we need the WG's agreement AND the W3C Director's permission to progress the CR, the actual CR is not scheduled to be published until Jul 5.

**Comment by ddorwin** [comment]
For completeness in the "persistent-usage-record" entry, we may want to specifically mention the [MediaKeySession Destroyed](https://w3c.github.io/encrypted-media/#media-key-session-destroyed) algorithm from PR #172 since it would be empty without the feature.

**Comment by ddorwin** [comment]
We should mark support for insecure contexts at risk to give us the option to remove support during CR (see #220). This could involve removal of the "Are insecure contexts allowed?" algorithm in addition to the step that calls it.

**Comment by jdsmith3000** [comment]
@ddorwin List now includes readyState and insecure context features.  I've wrapped the links with some additional text.  Please review for accuracy.

@paulbrucecotton This is still draft...

**Comment by jdsmith3000** [comment]
I am reopening to pickup a wording change requested by @paulbrucecotton.
