### ISSUE TITLE
Consolidate requirements and recommendations related to persistent data

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#211]
The spec has a number of sections that describe potential issues with various types of persisted data and described requirements and recommendations for mitigating them. Some reference each other while others do not, often duplicating or providing similar content. Some of these were identified in #168, and while the fix for that increased the coverage, it did not consolidate the sections. This issue tracks that work.

Specific examples:
* The mitigations in [Information Stored on User Devices](https://w3c.github.io/encrypted-media/#privacy-storedinfo) have a lot of overlap with [Allow Persistent Data to be Cleared](https://w3c.github.io/encrypted-media/#allow-persistent-data-cleared).
   - The former is referenced by Referenced by Media Keys' Storage and Persistence section
* [Incomplete Clearing of Data](https://w3c.github.io/encrypted-media/#incomplete-clearing) has a lot of overlap with [Allow Persistent Data to be Cleared](https://w3c.github.io/encrypted-media/#allow-persistent-data-cleared) or vice versa.
* As an easy to find example, `[COOKIES]` is referenced nine times.

**Comment by mwatson2** [comment]
Should do #210 first.

**Comment by ddorwin** [comment]
#210 is closed, so this is unblocked. We should coordinate around #301, though.

**Comment by jdsmith3000** [comment]
The problem here results from a heavy overlap between [Implementation Requirements](https://w3c.github.io/encrypted-media/#implementation-requirements) and [Privacy](https://w3c.github.io/encrypted-media/#privacy).  The mitigations for [Identifiers](https://w3c.github.io/encrypted-media/#identifier-requirements) pretty much mirror those for [Information Stored on Devices](https://w3c.github.io/encrypted-media/#privacy-storedinfo).

I have mixed feelings about whether these need to be fixed.  The spec could be more streamlined if sections are consolidated, but most of the overlap is at least consistent.  If we remove the overlap, in which section should the requirements detail reside:  Implementation or Privacy?

**Comment by mwatson2** [comment]
My suggestion is that we move all the relevant requirements into the "Implementation Requirements" section and then reference that from the Privacy section. I think it's clearer if all the actual requirements are collected together.

The Privacy section would eventually become mostly informative, explaining the issues, which ones have been addressed and which have not (if any) and referring to the implementation requirements for the details of how. I don't think we will get that far for V1, but we can make a start.

**Comment by jdsmith3000** [comment]
I don't see any functional benefit in cleaning this up in V1, and believe it should be marked VNext.

**Comment by mwatson2** [comment]
I created a PR for this (#310). @jdsmith3000 Do you still think we should leave this for VNext ?

**Comment by jdsmith3000** [comment]
I'll review the PR and respond.

**Comment by jdsmith3000** [comment]
PR is fine with me.  My VNext recommendation was based mainly on timing/priority of fixing this now.
