### ISSUE TITLE
Add more specific text about ensuring the desired privacy and cryptographic properties of identifiers

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#219]
We need to address the following ISSUE boxes in the spec.

In **[Encrypt Identifiers](https://w3c.github.io/encrypted-media/#encrypt-identifiers)**:
>Add more specific text about ensuring the desired privacy properties when encrypting identifiers.

In **[Use Per-Origin Identifiers](https://w3c.github.io/encrypted-media/#per-origin-identifiers)**:
>Add more specific text about ensuring the desired non-reversible properties.

**Comment by mwatson2** [comment]
Regarding the properties of encrypted identifiers, would it be sufficient to say that no two instances of the encrypted identifier must be associable by any entity not in possession of the decryption key ?

Regarding the non-reversible properties of derived per-origin identifies:

> Values across origins must be non-associable by applications, meaning it must not be possible to correlate identifiers from multiple origins, such as to determine that they came from the same client or user. Specifically, implementations that derive per-origin identifiers from an origin-independent identifier, must do so in a non-reversible way.

Similarly, perhaps instead of staying that these must be derived in a non-reversible way, wouldn't it be sufficient to say they must be derived in a way which guarantees the non-associable property required by the previous sentence ?

**Comment by mwatson2** [comment]
I created PR #266 with the above proposal.

**Comment by steelejoe** [comment]
How precise should the language be here? To paraphrase the NIST docs on cryptographic hashes, it seems like it would be fine to say "Non-reversible means that it is easy to compute the identifier from the values, but it is extremely difficult to reproduce the values from the identifier, or to find another set of values that will produce the same identifier."

We could also reference by example e.g. "Association of the identifier back to its original set of client values must be at least as difficult as finding a collision for a cryptographic has of the input values."

**Comment by mwatson2** [comment]
@steelejoe My proposal is that we don't define non-reversible but just say that the approach has to fulfill the "non-associable" definition that we added earlier (which itself includes language about it being "difficult" to associate).

**Comment by ddorwin** [comment]
@sleevi, any additional comments or suggestions?
