### ISSUE TITLE
Complete review of  security and privacy considerations sections

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#221]
We need to address the following ISSUE box in the [Status of This Document](https://w3c.github.io/encrypted-media/#h-sotd) section of the spec.

>This specification contains sections for describing [security](https://w3c.github.io/encrypted-media/#security) and [privacy](https://w3c.github.io/encrypted-media/#privacy) considerations. These sections are not final and review is welcome.

**Comment by mwatson2** [comment]
That text note was added quite some time ago. Do we think there has since been sufficient review ?

**Comment by ddorwin** [comment]
@josephlhall, these are the sections I referenced in https://github.com/w3c/encrypted-media/issues/158#issuecomment-209669987.  They should be fairly stable now that we've addressed most V1 issues. Some of the [Implementation Requirements](https://w3c.github.io/encrypted-media/#implementation-requirements) section is probably also relevant.

**Comment by ddorwin** [comment]
FYI, remaining V1 issues #110, #117, and #226 may affect these and related sections.

**Comment by josephlhall** [comment]
@ddorwin great, so now that it's stable, it's good time for PING review? Thanks to all for your work here.

**Comment by steelejoe** [comment]
+1 -- great work on this. 

I have some nit-picky comments. Should be relatively easy to address. 

Section 10.3.2 Mitigations
TLS -- "Furthermore, origin-specific permissions in combination with a secure origin, **ensure** that permissions granted to an application **cannot be abused** by a network attacker.". This language is too strong. We can safely say that TLS makes abuse far less likely, but not impossible. This should be changed to "Origin-specific permissions in combination with a secure origin make abuse of permissions granted to an application by a network attacker far less likely.".

Section 10.4.2 Mitigations
This section is marked as non-normative, but I am not clear why. Is it the "recommendations"? The use of normative "SHOULD NOT" in it was confusing me. 

Section 11.4.2 Mitigations  "Expiring stored data" NOTE
"For example, a user agent could be **configured to such data** as session-only storage, deleting the data once the user had closed all the browsing contexts that could access it.". This should be changed to "configured to **store** such data" I believe.

Section 11.4.2 Mitigations "Shared blacklists"
This section is unclear. What is a "Key System origin"? Does this refer to the dotted identifier for the Key System itself, in which case a blacklist seems like overkill since there are only a small number of Key Systems. Or does this refer specifically to use a particular Key System on an application origin? The latter seems more likely. If that is the correct interpretation this should be changed to "User agents may allow users to share blacklists of application origins and/or Key Systems". 

Section 11.4.2 Mitigations "Per-origin user alerts / prompts and permissions"
This sentence "User agents must prompt or otherwise inform the user before allowing use of a Distinctive Identifier that is not unique per-origin and/or not clearable is used. " is unnecessary based on the note following. Why not just remove it and the note? Apologies if this has been discussed in depth -- I did not see it. 

Section 11.7 Private Browsing Modes 
Spelling error -- "The privacy concerns discussed in previous sections may be **expecially** concerning for users employing such modes."

**Comment by ddorwin** [comment]
Addressing some of the low-hanging fruit in @steelejoe's comments:

>Section 10.4.2 Mitigations
>This section is marked as non-normative

10.4.1 Potential Attacks is non-normative, but the Mitigations section is normative.

>This should be changed to "configured to store such data" I believe.

Fixed in the commit above.

>Spelling error -- "The privacy concerns discussed in previous sections may be expecially concerning for users employing such modes."

Fixed in the commit above.

**Comment by ddorwin** [comment]
>@ddorwin great, so now that it's stable, it's good time for PING review? Thanks to all for your work here.

@josephlhall, yes. The issues I mentioned have been closed, but there are other more minor ones you might want to follow or comment on. I've tried to ensure they start with "Privacy:". Maybe we should add a GitHub label as well. See also the conversation beginning at https://github.com/w3c/encrypted-media/issues/110#issuecomment-224845536.

**Comment by ddorwin** [comment]
@josephlhall and others. The published timeline has us completing the PR draft in two weeks. I you wish to review these sections or comment on them, please do so ASAP.

<br/>Note: I moved the remaining feedback from @steelejoe to #273.

**Comment by ddorwin** [comment]
FYI, here's a link to [open issues with "privacy" in the title](https://github.com/w3c/encrypted-media/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20privacy%20in%3Atitle).

**Comment by steelejoe** [comment]
Looks good. Were there objections to the other bits or just moving off to make the processing easier?

**Comment by plehegar** [comment]
Unlike someone speaks up, the reference to this issue will be from the status of the document. It seems that the work on security and privacy was considered enough to move forward.

**Comment by ddorwin** [comment]
@steelejoe, It was just to make the processing easier (and accelerate implementation) and separate it from "review," which seemed like a larger task.

**Comment by ddorwin** [comment]
PR #300 implements https://github.com/w3c/encrypted-media/issues/221#issuecomment-233681688.

Feedback is still welcome, but please open new specific issues.
