### ISSUE TITLE
Access of session's "record of key usage" in the MediaKeySession Destroyed and Session Closed algorithms is inconsistent

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#225]
The current access of a session's _record of key usage_ are:

1. `generateRequest()`, `remove()`, and `update()` algorithms: By the CDM and in parallel to the main event loop
1. Attempt to Decrypt algorithm: By the CDM within the playback algorithms, which must run in parallel to the main event loop
1. Session Closed algorithm: By the **user agent** in a task, which runs **on the main event loop**
1. MediaKeySession Destroyed algorithm: By the **user agent** in parallel to the main event loop

This session state is managed by the CDM, which always operates in parallel to the main event loop. Thus, it should either be explicitly provided to the user agent algorithm by the CDM (i.e. "Run the Foo Bar algorithm, passing _record of key usage_.") or accessed by the the CDM in parallel. In the latter case, the CDM could perform the operation or be used to obtain the value.

The fix for (4) could be as simple as moving the last two steps under a "Use the _cdm_ to execute the following steps:" step. (3) is more complex because the algorithm is running in a task on the main event loop. If ordering with the other events and the promise in that method are important, just running the step in parallel could be problematic.

**Comment by mwatson2** [comment]
I think this issue should be V1NonBlocking since the proposed changes have no page-observable effects.

When we say "use the CDM" we highlight that the CDM may be involved (i.e. unspecified functionality may be involved) but we do not pre-suppose an exact functional split or communication / execution model. I agree we need to say "Use the CDM" to store the _record of key usage_ for (3) and (4).

When we say "in parallel" we mean only that page script may execute before the "in parallel" steps and so page-observable effects of the parallel steps may not be immediately observed by the page. 

If the steps in question have no page-observable effects, or if those effects are observable only through asynchronous notification to the page anyway, then whether we say "in parallel" or not has no effect.

It may be worth clarifying in _Session Closed_, as we do in _MediaKeySessionDestroyed_, that the storage of the _record of key usage_ may happen asynchronously.

**Comment by jdsmith3000** [comment]
@ddorwin @mwatson2 I believe we agreed today with mwatson2's request that this be V1NonBlocking.  I've marked it as such.

**Comment by mwatson2** [comment]
I created a PR #232.
