### ISSUE TITLE
CDM implementations must support multiple keys per session

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#23]
In Bug 25092, Mark says, "there are DRM systems which do not support multiple keys or key ids for the same session" ([comment 8](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25092#c8)) and "there are CDMs that support only a single key or only a single key at a time" ([comment 30](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25092#c30)).

Such CDM implementations would break interoperability, especially for some common use cases. For example, applications that use multiple keys (i.e. different keys for audio and video) would either not support clients with such CDMs or need key system-specific logic to support them. In theory, such an application could use a separate session per key, but that would introduce overhead. In addition, applications may rely on a single session/license for tracking active licenses.

Such CDM implementations also break the intended behavior and usage of the keyStatuses attribute (see [Bug 25092 comment 33](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25092#c33)).

Unless we have some baseline requirements, authors will have a difficult time writing interoperable applications.

**Comment by tc0312** [comment]
Regarding to "In theory, such an application could use a separate session per key"
If application is supposed to reuse the same session over and over, what's the value of having MediaKeysSession? Can't we just merge MediaKeys and MediaKeysSession?

**Comment by tc0312** [comment]
I will give it another take.

I have given more thought on this requirement.
I don't think EME spec should mandate this as key is an implementation detail in the DRM system.
Also, from the perspective of an application author, supporting multiple keys will not make EME more easier to use. (Ignoring output protection in this discussion because exposing key status isn't the only way to expose output protection status.)

Applications shouldn't know about any implementation details of the DRM system. This is necessary to make the same code to work across multiple CDMs. The only thing an application should take part is doing the licence exchange. It shouldn't know about the format of the licence request, the licence and the decryption keys. They are just blobs to the application. Whether the licence blob contains single or multiple keys does not concern the application. 
If we expose the concept of keys to the application, application authors will have to write CDM implementation specific logic to make it work universally. This is because each DRM has a different definition of licence & keys. For example, PlayReady and Widevine support resolution-aware output protection policy while Adobe Access doesn't. To achieve the same content protection, different number & definition of keys must be used in different DRM system. Application authors will have to write different handling for each CDM.
Exposing keys to the application layer is not a good idea.

However, it helps application authors a lot if the spec requires CDM to be able to decode a stream with a single licence/MediaKeySession, with regardless of number of keys.
With this requirement, applications can simply throw away the current session and create a new one whenever it switches content, making life cycle management very easy.
I will reply separately for detecting output protection status.

(Off topic: if MediaKeySession represents a licence, should it be renamed?)

**Comment by ddorwin** [comment]
>Regarding to "In theory, such an application could use a separate session per key"
If application is supposed to reuse the same session over and over, what's the value of having MediaKeysSession? Can't we just merge MediaKeys and MediaKeysSession?

The intent has always been that sessions can contain any number of keys and that different sets of keys can be obtained and managed independently via sessions. Depending on their needs (See below), applications can choose to put all keys in one session or each key in a separate session.

In the quoted text, I was saying that this is a theoretical workaround for CDM implementations that only support a single key. This bug is saying that such implementations should not be allowed, and thus, this workaround should not be necessary.

>Applications shouldn't know about any implementation details of the DRM system. This is necessary to make the same code to work across multiple CDMs. The only thing an application should take part is doing the licence exchange. It shouldn't know about the format of the licence request, the licence and the decryption keys. They are just blobs to the application.

I mostly agree, and that is the intent of this bug.

>Whether the licence blob contains single or multiple keys does not concern the application.

This is where we disagree. The application is responsible for making license requests - whether in response to an `encrypted` event or based on a priori knowledge. For CDMs that support multiple keys, the application would make a single request for all keys. If there exist CDMs that support only a single key per session, the application would need to have special logic to make multiple requests and manage the resulting sessions.

There would also be additional server-side complexity, especially for content providers that track issued licenses as part of their business logic.

We know that some application authors will want multiple keys per session. We need to ensure that they can implement applications that require this in an interoperable way without CDM-specific workarounds.

>If we expose the concept of keys to the application, application authors will have to write CDM implementation specific logic to make it work universally. This is because each DRM has a different definition of licence & keys. … To achieve the same content protection, different number & definition of keys must be used in different DRM system. Application authors will have to write different handling for each CDM.

The definition of key ([as used in the EME spec](https://w3c.github.io/encrypted-media/#decryption-key)) is common and does not differ across DRM systems. Keys are a property of the content. The container specifies which key (via key ID) is to be used to decrypt a given block. Assuming the same content streams will be used for all key systems (this is fundamental to EME), the same keys and number of keys will be used for all key systems.

>For example, PlayReady and Widevine support resolution-aware output protection policy while Adobe Access doesn't.

I don’t believe this is universally true. However, inconsistent support is one of the reasons I oppose explicitly exposing such capabilities (issue #22).

**Comment by tc0312** [comment]
> If there exist CDMs that support only a single key per session, the application would need to have special logic to make multiple requests and manage the resulting sessions.

My proposed requirement forbids that.
> CDM must be able to decode a stream with a single licence/MediaKeySession, with regardless of number of keys.

This requirement achieves the same thing, without requiring CDM to support multiple keys. It leaves more room for CDM implementers. Isn't it better?

**Comment by ddorwin** [comment]
>>CDM must be able to decode a stream with a single licence/MediaKeySession, with regardless of number of keys.
>This requirement achieves the same thing, without requiring CDM to support multiple keys. It leaves more room for CDM implementers. Isn't it better?

This is better than nothing (and one possible outcome of this bug), but we'd need to ensure it addresses all the related use cases.

I assume that such a solution would involve the user agent wrapping multiple licenses in a session and interface with the underlying DRM implementation to present the multiple licenses. An application could also make a single request for multiple keys. Again, the user agent would need to generate multiple requests and send them back as a single message to the server. The server would need to support wrapping and unwrapping multiple requests into a single session. Servers and user agents would need to be careful to avoid interoperability problems, such as different expiration times in the underlying licenses.

We'd still need to address the license tracking issue. Perhaps the server that is doing the wrapping could ensure that the licenses are treated as a single license that is considered outstanding until all underlying licenses have been destroyed.

**Comment by tc0312** [comment]
> I assume that such a solution would involve the user agent wrapping multiple licenses in a session and interface with the underlying DRM implementation to present the multiple licenses. An application could also make a single request for multiple keys. Again, the user agent would need to generate multiple requests and send them back as a single message to the server. The server would need to support wrapping and unwrapping multiple requests into a single session. Servers and user agents would need to be careful to avoid interoperability problems, such as different expiration times in the underlying licenses.

My requirement makes the CDM to do the wrapping.

In your example, initData should be wrapped to contain information for multiple keys at encryption time. The DRM vendor has to make sure its CDM is able to understand the wrapped initData and is able to generate a wrapped challenge. Also, DRM Server is built with DRM vendor provided library so it shouldn't have any issues understanding the wrapped challenge.

This is only necessary if someone is trying to decrypt a stream encrypted with multiple keys with a single key DRM solution. Which is really rare because if supporting a single key DRM solution is necessary, usually for backward compatibility, application developer will just encrypt video assets with a single key.

Anyway, CDM is required to handle everything (wrapping or whatever). It's transparent to UA and App.

**Comment by ddorwin** [comment]
>In your example, initData should be wrapped to contain information for multiple keys at encryption time. 

initData generally only contains the key ID for that stream (or segment of the stream). It doesn't scale to include the key IDs for all streams for a title in each of its streams.

I guess my "single request for multiple keys" idea would only work if the application was using [`"keyids"`](https://w3c.github.io/encrypted-media/keyids-format.html) because that would allow the user agent to break up the request. Another option might be for the user agent to make three requests for the same initData, but I don't know whether these CDM implementations would check that the key IDs in the resulting licenses match the request.

>The DRM vendor has to make sure its CDM is able to understand the wrapped initData and is able to generate a wrapped challenge. 

If the CDM on the client can be updated to do that, why can't it just provide native support for multiple keys? Perhaps it depends on whether you consider the "CDM" to be updatable software sitting on top of a DRM implementation or the DRM implementation.

>This is only necessary if someone is trying to decrypt a stream encrypted with multiple keys with a single key DRM solution. 

This bug isn't about a single stream with multiple keys (that would be key rotation) - it's multiple streams for the same title encrypted with different keys.

>Which is really rare because if supporting a single key DRM solution is necessary, usually for backward compatibility with embedded devices, application developer will just encrypt video assets with a single key.

Using a single key does not scale to the web platform and is harmful (assuming one requires different levels of protection for different streams). See issue #22.

>Anyway, CDM is required to handle everything (wrapping or whatever). It's transparent to UA and App

Transparency to the app is the goal. It's possible that the UA will need some knowledge to adapt to a CDM implementation. However, it's unclear why the CDM would handle wrapping, etc. rather than implementing support for multiple keys.

**Comment by ddorwin** [comment]
In #22, @tc0312 wrote:
> However, the fake key solution might not work on current PlayReady and Adobe Access because they use single key licenses.

@jdsmith3000, @steelejoe: Is it true that PlayReady and Adobe Access do not support more than one key per license?

If so, how do these systems support applications (native or EME) that need multiple keys? 

Also in #22, @mwatson2 claimed
>... none of the existing CENC-supporting DRMs have the ability to have multiple keys delivered and used for seamless playback...

This is not true for Widevine. Is it true for your systems?

**Comment by steelejoe** [comment]
Adobe Access can load multiple keys from a license request. So a single session can have many usable  keys simultaneously loaded. 

Regarding the definition of Key -- I still have a problem with this definition that I have raised before. Specifically this line "Such keys must only be provided to the CDM via an update() call." as this is unnecessarily restrictive. 

Regarding requesting multiple keys -- there are at least two ways that a CDM could support this without any application support beyond what the spec already requires. A CDM that can only request a single key at a time can simply generate key requests and receive the updates until all the keys needed are satisfied. Or if the CDM supports this, it can request a set of keys in a single request. In either case, the end result is the same.

**Comment by ddorwin** [comment]
I think there are no remaining actions here. Feel free to re-open if you disagree.
