### ISSUE TITLE
Explicitly state that distinctive and permanent identifiers may not be used without distinctiveIdentifier being "required"

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#248]
We have algorithmic steps that say whether distinctive and permanent identifiers may be used, but I don't believe we have a clear statement in the definition of these identifiers that says they are only accessible when the MediaKeySystemAccess has `distinctiveIdentifier="required"`.

Even a non-normative note clearly stating this might be helpful for the reader.

It might also be helpful to include this in places that reference these types of identifiers, such as the individualization section.

**Comment by mwatson2** [comment]
This seems like duplicating requirements, which I feel we already do too much. It becomes unhelpful to the reader because they are used to seeing things duplicated and then make assumptions when something is missing. It would be better to have each requirement in exactly one place (preferably a place where the reader would expect it to be).

Another problem with duplication is that as we make changes it becomes hard to keep everything in sync.

**Comment by ddorwin** [comment]
@mwatson2, I think it is important to reference the control from at least the things that are controlled (and specifically mentioned in the control's definition). While we have many references to DI, DPI, and use of DI/DPI, there is no link from those to the control.

PR #295 adds a few non-normative notes that reference the control and provide the most important information to the reader. Let me know what you think.
