### ISSUE TITLE
Problem about MediaKeySession.keyStatuses get/has methods.

### ISSUE THREAD

**Issue by jwwang** [w3c/encrypted-media#25]
MediaKeySession.keyStatuses is a read-only maplike which has get/has methods. The get/has methods of a map object compare keys by its object id instead of the object content. I think it is hardly useful if we compare by object id instead of object content. However, the maplike spec doesn't say anything about that. I think MediaKeySession.keyStatuses should return a sequence of [BufferSource,MediaKeyStatus] pairs so we don't have to worry about the key order and how keys are compared.

**Comment by jwwang** [comment]
Here is an example of Map.get() which compares keys by its object id instead of object content.

  var map = new Map;
  var bytes = new Uint8Array(2);
  var bytes2 = new Uint8Array(bytes);
  map.set(bytes, 5);
  alert(map.get(bytes));  // alerts 5
  alert(map.get(bytes2)); // alerts undefined

**Comment by ddorwin** [comment]
I confirmed the above behavior in Chrome 40 and 42. I agree that this is not useful, especially since the key is set by the user agent (meaning there can never be a match).

Chromium's implementation of `keyStatuses` compares the actual values, meaning get() and has() work as desired.

http://heycam.github.io/webidl/#idl-maplike does not say how keys should be compared, but it does say
>Maplike interfaces support an API for querying the map entries appropriate for the language binding.

and
> In the ECMAScript language binding, the API for interacting with the map entries is **similar** to that available on ECMAScript Map objects.

We should get clarity on the intended behavior from a Web IDL point of view. Comparing the actual values is certainly more useful, especially for readonly maplikes, but it is inconsistent with with ECMAScript Map objects. Note that the API is supposed to be **similar**.

**Comment by bzbarsky** [comment]
> http://heycam.github.io/webidl/#idl-maplike does not say how keys should be compared

You're looking at the wrong spec section.  The right spec section is http://heycam.github.io/webidl/#es-maplike which defines the behavior in great detail and in particular defines it in terms of delegation to an actual ES Map object.  So the key comparison behavior is the key comparison behavior of ES Map.

Comparing the "actual values" would involve defining what "values" means for the various things you can use as key types, including arbitrary objects and so forth, right?

**Comment by ddorwin** [comment]
Specifically, steps 8-10 of http://heycam.github.io/webidl/#es-map-get-has and the ECMAScript type mapping for buffer source types at http://heycam.github.io/webidl/#es-buffer-source-types.

If we wanted to allow it, the prose could specify what the actual key values are for `maplike` objects. For buffer source types, that's pretty easy to do.

More generally, `maplike` is not useful when the key type is an object (or probably otherwise not primitive types). This should probably be called out in http://heycam.github.io/webidl/#idl-maplike. Could it be prevented via the Grammar? I will file a bug.

**Comment by ddorwin** [comment]
Assuming the above is not going to change, we almost certainly don't want to use `maplike` for the `keyStatuses` attribute.

Options include:
1. Define our own map interface directly (as Web MIDI currently does: http://webaudio.github.io/web-midi-api/#midiinputmap-interface).
2. Use a primitive type for the key - likely a string with either the text representation or base64url encoding of the key ID.
3. A `sequence` of [`BufferSource`,`MediaKeyStatus`] pairs like @jwwang proposed.

I prefer one of the first two options because I think `get()` and `has()` will be useful for applications. The third option forces applications to iterate or implement this functionality themselves.

**Comment by bzbarsky** [comment]
> More generally, maplike is not useful when the key type is an object

Why not?  It's fine if the key is a Node, say.  Your problem is that you're using objects to represent what should be more like value types (which ES doesn't have yet, so it's not like you have any other options).  You don't care about the particular objects any more than you would about a particular Date object you have; you care about the internal data buffer (or in the case of Date the internal timestamp)....

I do suggest bringing this issue up on public-script-coord and seeing what people have to say.

**Comment by ddorwin** [comment]
>I do suggest bringing this issue up on public-script-coord and seeing what people have to say.

https://lists.w3.org/Archives/Public/public-script-coord/2015JanMar/0148.html
I may not have adequately covered the value types and lack of ES support for them. Please add that and anything else you think might be relevant to the discussion.

**Comment by ddorwin** [comment]
Issue #39 proposes to avoid maplike (because of this issue), making this issue obsolete.
