### ISSUE TITLE
Secure origin check should not use "incumbant" settings object

### ISSUE THREAD

**Issue by mwatson2** [w3c/encrypted-media#269]
Things have changed: "current settings object" is apparently now the right thing:

https://readable-email.org/list/public-script-coord/topic/multiple-globals-and-you

https://github.com/whatwg/html/issues/1430

@dontcallmedom

**Comment by ddorwin** [comment]
From #270:
>https://w3c.github.io/webappsec-secure-contexts/#new has updated the recommended language. See https://readable-email.org/list/public-script-coord/topic/multiple-globals-and-you for details.

In addition, there is an alternative/additional recommendation to use `[SecureContext]` in the IDL. (There is a question about whether to use one or both methods in https://github.com/w3c/webcrypto/issues/28#issuecomment-232805001.)

If we maintain the algorithm check, we may want to reject the promise rather than `NotSupportedError` with `SecurityError` as suggested in the recommended language.

**Comment by ddorwin** [comment]
Per https://github.com/w3c/webcrypto/issues/28#issuecomment-232857255, `[SecureContext]` in the IDL is sufficient.

**Comment by ddorwin** [comment]
#271 uses `[SecureContext]`, which allowed us to eliminate the text covered by this issue, making it obsolete.
