### ISSUE TITLE
load() algorithm: Checking "support [for] loading previous sessions" is redundant

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#27]
Step 5 of the `load()` algorithm is currently:
>>If the Key System implementation represented by this object's cdm implementation value does not support loading previous sessions, return a promise rejected with a new DOMException whose name is NotSupportedError.

However, support for the session type for this object was already checked in `createSession()` and all persistent session types must be loadable. Thus, this step is redundant and can be removed.

**Comment by steelejoe** [comment]
Can you clarify what is going to happen here? Are you saying that because the browser already knows the answer the capability check does not need to happen again? If so -- that I agree with. But I am still curious what happens if a load() is called. I assume the API will still be available. So what will be returned?

**Comment by ddorwin** [comment]
The user agent already performed the check in `createSession()`. If the session was created, the `sessionType` is supported.

Step 4 of the `load()` algorithm checks whether the session's type is loadable. For implementations that do not support loading session (old step 5), this step will always fail because the session's type will never be one of the loadable types.
