### ISSUE TITLE
Remove requirement to close CDM session *before* destroying UA MediaKeySession state

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#358]
https://w3c.github.io/encrypted-media/#mediakeysession-interface says the following:
>If a `MediaKeySession` object becomes inaccessible to the page and is not closed, the User Agent MUST use the CDM to close the session **before User Agent state associated with the session is deleted**.

Is there a reason that the CDM session needs to be closed before deleting related UA state (the bold text)? There is no application-visible difference in when the CDM session is closed.

We ran into this while implementing this step. All CDM interactions are asynchronous and we're not going to block destruction of the `MediaKeySession`, so we will ignore the the bold text anyway. It seems like a superfluous requirement that we should just remove.

**Comment by mwatson2** [comment]
The intention was to capture the fact that some state is necessary to close CDM session, specifically (at least) the identity of the session to be closed. Note that it does not say `MediaKeySession` state, which might imply that the `MediaKeySession` JS object must be maintained.

I believe it was your comment that the CDM session could not be closed at some later time if all User Agent state associated with the session had been deleted. 

So, I am fine with removing the bold part, or clarifying that it refers only to state that is necessary to close the CDM session, provided that we're not going to see a comment in future that the CDM session cannot be cleanly closed at this time because the UA state that identifies it has been deleted.

I imagine in your implementation, where the CDM session closing is asynchronous, you are _sending the User Agent state necessary to close the CDM session to the CDM_. So you are not deleting it and IMO are compliant to the bold text.

**Comment by ddorwin** [comment]
This paragraph was added in https://github.com/w3c/encrypted-media/commit/3b73f31e0c59c4715fef57874deea8267d68d5b2, and I think this language is specific to the removed MediaKeySession Destroyed algorithm.

Since unclosed `MediaKeySession` objects are not destroyed until the corresponding `MediaKeys` session, the current text does not impact the observable behavior* because the keys are then inaccessible to the application. Still, it doesn't hurt to note that the corresponding CDM key session is closed as a result. PR #359 changes the language to be consistent with the other place where we close the session.

<br>* Authors may interpret this text as having the following implications:
 1. Destroying keys. However, even in an explicit `close()` request, key destruction/usage is really a matter of CDM robustness and ultimately enforced by the license policy.
 1. Freeing resources. However, applications can't really rely on how quickly such resources will be freed via garbage collection, just that they shouldn't leak over time. An application that is concerned about resources should call `close()` and wait for the returned promise to be resolved.
