### ISSUE TITLE
Formal Objection: I do not accept these terms of service

### ISSUE THREAD

**Issue by dontplease** [w3c/encrypted-media#384]
The web was originally conceived to be a free, as in libre, space, but increasingly there have been stricter and stricter restrictions, nooses tightened around the throats of the users, creators, and citizens of the 'net all for the benefit of none, but the blood god Profit. 

Adding an EME standard is a further erosion of that ideal and a blow to freedom both on and off-line. There is no conceivable purpose for adding a DRM standard to the web as a whole, other than restriction, control and eternal copyright. If companies or private persons want to restrict and 'protect' their content they are free to do so (or try), but the creation of this as a world wide standard is a grave mistake. 

Please do not do this.

**Comment by benbucksch** [comment]
+1

**Comment by plehegar** [comment]
EME does not add DRM to the Web:
* DRM support was added by plugins in the first place and you'll still find video content that necessitates their uses. The exposure in using plugins is way greater than in using EME, since plugins are much more than just DRM.
* EME does not require the support of any DRM system. It does however enable the use of underlying DRM  systems in a much more controlled way than what plugins are doing.  EME only require the clear key system, which could be implemented in free software.

**Comment by GravisZro** [comment]
> * The exposure in using plugins is way greater than in using EME, since plugins are much more than just DRM.

This brings up an excellent point about the absolute lack of security regarding CDMs **because there is no specification for CDMs.**

> * EME does not require the support of any DRM system. 

A better point is that CDMs _cannot_ be supported by all browsers **because there is no specification for CDMs.**

**Comment by plehegar** [comment]
@GravisZro I agree that having a CDM specification would be an improvement. The idea was circulated and didn't receive much support and, as far as I know, only PlayReady from MSFT released their CDM interfaces in the open.

**Comment by GravisZro** [comment]
@plehegar 
The idea didn't receive any support because **all the people in the WG are being paid** to ensure certain DRM can be used which screams conflict of interest.  This is 100% about DRM.  If the WG was composed of objective individuals, they would have no interest in the EME being standardized.

**Comment by Oflameo** [comment]
@plehegar is there any use case for encrypted media extensions for something that doesn't have digital restrictions management?

**Comment by plehegar** [comment]
@GravisZro A lot of people are getting paid to work on Web specifications, being DRM related or not, so I'm not sure I understand your point.

@Oflameo EME is specifically targeted for protected content.

**Comment by benbucksch** [comment]
> @GravisZro A lot of people are getting paid to work on Web specifications, being DRM related or not, so I'm not sure I understand your point.

Obvious bias. If a Mozilla employee helps to create standards, there is no clear interest other than advancing the web. OTOH, DRM is an interest *against* users, inherently. Netflix is a website/service, and not independent.

> @plehegar is there any use case for encrypted media extensions for something that doesn't have digital restrictions management?
> @Oflameo EME is specifically targeted for protected content.

Given that the entire nature of DRM is to enforce something against users, on their own machines, and EME is made for than DRM (as you admit, thank you for being honest), that means that EME is inherently against user interests. For that reason alone, it should be rejected as standard.

Enforcing something against the user on their own hardware is not a winning idea. And this inherent problem causes all the downfall problems that we're discussing in other objects (e.g. open source, new browsers etc.).

This is not without alternative. There are other ways to protect content, e.g. watermarks to track offenders. The music industry learned it the hard way that DRM does not work, and they now sell MP3s. And make more money than before.

Hollywood simply **chose** to force DRM on everybody against their will. Why should W3C side with a system that is geared against end users and against their own systems?

**Comment by plehegar** [comment]
> Obvious bias. If a Mozilla employee helps to create standards, there is no clear interest other than advancing the web.

Yet, Mozilla does support EME so someone implemented it there.

> Apparently, W3C does not listen to users (represented e.g. by EFF and others who spoke up against this).

This might surprised you but users is one of the main reason why W3C got involved in EME. We knew EME would happen, no matter what, so we decided that it was better done in an open forum rather than behind closed doors in some obscure TV consortium. We also listen to all of the input we receive, not just from the EFF and others who spoke up against this.

> Given that the entire nature of DRM is to enforce something against users, on their own machines, and EME is made for DRM (as you admit, thank you for being honest), that means that EME is inherently against user interests. For this reason alone, this standard should be rejected.

Will you then suggest to the users that they should use native apps to be able to see the content, or tell them that they shouldn't see the content at all? I'm curious to understand if and where you see the alternatives here.

**Comment by GravisZro** [comment]
@plehegar 
> A lot of people are getting paid to work on Web specifications, being DRM related or not, so I'm not sure I understand your point.

The people from this WG are not being paid to improve the internet, they are being paid to push a very specific agenda.  Do note the constant refusal of a CDM specification because it doesn't fit their agenda.

> Yet, Mozilla does support EME so someone implemented it there.

Mozilla is a business.  Note that there are no browsers with the EME that are not corporately backed.

> This might surprised you but users is one of the main reason why W3C got involved in EME.

Even a fool can see that the reason is the W3C is involved with the EME is that it's funding was at risk if they refused.  Everything else is simply a justification for going along with it.

> Will you then suggest to the users that they should use native apps to be able to see the content, or tell them that they shouldn't see the content at all?

* Absolutely.
* Things were fine before the EME ever was.
* It's not the job of the W3C to enable a particular business model.

> Got any pointer on watermarks to track offenders?

Make the watermark include the source of the content and user identifier.  That way you know where it came from and who originally distributed it.  In addition, you could make DMCA noticed automated with 0% false positives.  Honestly though, I don't care about the problems that hollywood studios have **knowingly** created in order to maximize profits.

**Comment by ShadowRZ** [comment]
So, what's your choice?

**Comment by Atavic** [comment]
**Alternatives**: Firefox EME Free
[
mac-EME-free
Win32-EME-free
Win64-EME-free](https://github.com/pyllyukko/user.js/issues/325)

GNU Icecat, [Palemoon](https://github.com/MoonchildProductions/Pale-Moon/pull/1211)...

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
