### ISSUE TITLE
Note in 8.7.3 Unencrypted In-band Support Content

### ISSUE THREAD

**Issue by plehegar** [w3c/encrypted-media#406]
The Note in section 8,.7.3 is confusing and loosing the intent of the specification. Most of the time, those tracks don't encrypted anyway. How about, replacing the note with the following text and move it after the second sentence:
[[
Note: While in practice accessibility tracks are rarely encrypted, this provision ensures that even in the case that such tracks might be encrypted, the accessibility information will be available to users once the media is decrypted.
]]

This replacement language clarifies how provision 8.7.3 helps ensure access to accessibility info, rather than raising the concern that info won't be available, since testing has demonstrated that the info does remain available.

**Comment by mwatson2** [comment]
The existing note warns that support of encrypted in-band content might not be there in UAs, which is useful information. I suggest:
- remove the existing note
- add "User Agents are not required to support decryption of in-band support content." after the first sentence
- add a slightly modified version of the note proposed above at the end of the section:

> Note: While in practice accessibility tracks are rarely encrypted, this provision ensures that even in the case that such tracks might be encrypted, and decryption is supported by the User Agent, the accessibility information will be available to users once the media is decrypted.

**Comment by swickr** [comment]
"... are not required to support ...." is sounding almost-normative to my ears.  The existing note is softer in that regard.  Perhaps "Decryption of such content by UAs is optional and [at the time of this specification] not generally supported."

**Comment by ddorwin** [comment]
I think the existing note and proposed note serve different purposes. The proposed note explains the importance of the last paragraph, but there is an important message for authors in the existing note: Because decryption of such content is not generally supported, "encrypting such tracks would prevent them from being widely available for use with accessibility features in user agent implementations." In other words, no or very few user agents would enable access to the tracks even if all user agents that do support decrypting the tracks support the requirement in the last paragraph.

**Comment by jdsmith3000** [comment]
I agree with David.  The intent of this section is to advise against encrypting in-band content like captions.  The proposed changes seem to say "if this content is encrypted, it will be available once decrypted".  That's clearly true, but it's hard to see what guidance it provides.

**Comment by brewerj** [comment]
I think that both points are needed. Developers need to know that the normative provisions (the "should" and "must" language) in this section is important, or else accessibility may be broken. That is what the original note accomplished.

OTOH, people concerned about accessibility need to know that the normative provisions in this section, if followed, will provide access to the accessibility information (captions, transcripts, description) accompanying a video. The original note does not make that clear.

Here is an approach to address both points. Amend the existing note to read: 

Decryption of such tracks - especially such that they can be provided back the user agent - is not generally supported by implementations. Thus, encrypting such tracks would prevent them from being widely available for use with accessibility features in user agent implementations. Following the normative provisions in this section ensures that even in the case that such tracks might be encrypted, the accessibility information will be available to users once the media is decrypted.

**Comment by jdsmith3000** [comment]
@brewerj:  Are you referring to this normative statement?
> Implementations that choose to support encrypted support content MUST provide the decrypted data to the user agent to be processed in the same way as equivalent unencrypted timed text tracks.

Is it clearer if it says this:

>**_To ensure accessibility information is available in usable form_**, implementations that choose to support encrypted support content MUST provide the decrypted **_in-band_** data to the user agent to be processed in the same way as equivalent unencrypted timed text tracks. 

The note seems best focused on clarifying the first paragraph that advises against decrypting these tracks.

Separate: There is a minor typo in the note currently:

> Decryption of such tracks - especially such that they can be provided back _**to**_ the user agent - is not generally supported by implementations. Thus, encrypting such tracks would prevent them from being widely available for use with accessibility features in user agent implementations.

**Comment by brewerj** [comment]
I think your proposal to add "To ensure accessibility information is available in usable form" before the MUST provision is an improvement in that it more prominently states the importance of the MUST provision, while also providing reassurance that accessibility info will be available in conforming implementations. 

Adding that phrase to the MUST statement would make the third sentence of my proposed amended Note unnecessary.

I don't think that it's necessary to add "in-band" as a descriptor for "data" in this phrase. The title of 8.7.3 ("Unencrypted In-band Support Content") already restricts the scope of this subsection to in-band data. And while out-of-band accessibility information (for instance, potentially community-provided improved captions or audio descriptions) isn't an issue because those can be synched via the unencrypted time code, reinforcing the emphasis on "in-band" in the MUST statement might lead some people to wonder whether 8.7.3 is only addressing the problem for some accessibility information, but leaving a problem for out-of-band data. I don't think that clarification helps. It might add confusion, or create a need for adding a further clarification of what happens with out-of-band accessibility information.

Ack, on the typo. Good to clean that up.

**Comment by ddorwin** [comment]
Jerry's proposed changes to the last paragraph in the section LGTM, though I also have concerns about the "in-band" reference. I think it should be moved to be before "support content" so that the terminology is consistent with the section name and first paragraph.

@brewerj, I think the question of encrypted out-of-band support content exists regardless. However, I don't think this is an issue for the spec since the spec only supports decryption of media data. It is not possible to provide other types of data to the CDM for decryption. Perhaps there should be a note clarifying this.

I also think that the current text is not technically complete. "Implementations" is the user agent, plus maybe the CDM, so it doesn't make sense for the implementation to provide decrypted data to the user agent. Also, there may not be an explicit requirement that the user agent actually process it that way.

Finally, the "timed text tracks" reference seems odd. The rest of the section has only addressed "in-band support content" and never referenced specific APIs. I think we should generalize this while maybe referring to this specific API.

I propose the following:
>**_To ensure accessibility information is available in usable form, for_** implementations that choose to support encrypted **_in-band_** support content **_, a) the CDM_** MUST provide the decrypted data to the user agent **_and b) the user agent MUST process it_** in the same way as equivalent unencrypted  **_support content. For example, to be exposed as timed text tracks [[!HTML51]]_**.

**Comment by jdsmith3000** [comment]
David's clarification makes sense to me.  I suggest a colon is the proper punctuation before the a)/b) comments though:

> To ensure accessibility information is available in usable form, for implementations that choose to support encrypted in-band support content: a) the CDM MUST provide the decrypted data to the user agent and b) the user agent MUST process it in the same way as equivalent unencrypted support content. For example, to be exposed as timed text tracks [[!HTML51]].

@brewerj Please confirm you agree with this wording as well.

**Comment by brewerj** [comment]
LGTM, & thanks for the improvements. 

Sorry for delay, wanted to confirm that the rewording would be a clarification only, not substantial, given stage of doc. Should be all set.

**Comment by jdsmith3000** [comment]
Thanks.  I'll do a PR.
