### ISSUE TITLE
Notification when playback is resumed from waitingForKey

### ISSUE THREAD

**Issue by tc0312** [w3c/encrypted-media#42]
In the current EME draft, when playback is resumed from waitingForKey, no event is fired. Applications don't know whether the key it has just loaded is unblocking video playback.

Applications need to know that to provide robust error handling.

A quick example: application can listen for the playback resume event. If the event hasn't fired after loading a key within a period, it knows that it has loaded the wrong key.

**Comment by cpearce** [comment]
Can we fire a "playing" event in when playback resumes?

**Comment by ddorwin** [comment]
See issue #7, which led to the current implementation.

The original comment assumes that the `waitingforkey` event is intended to be used as part of normal playback, but it "is primarily intended to indicate problems with playback (vs. being actionable by the application)." If this event occurs during playback, there is very likely to be a user-visible interruption, so applications should avoid situations that cause it.

If an application really wanted to know if playback had resumed, it could check the currentTime and related events.

Note: It appears that this event would also be fired before the first frame is rendered (i.e. shortly after the `encrypted` event) if playback is started without the appropriate keys. If keys are provided to update() that are not sufficient, another event should be fired (though there are normative permitted exceptions to running "the attempt to resume playback if necessary algorithm."

>Can we fire a "playing" event in when playback resumes?

No, see issue #7. Although not explicitly mentioned, the `playing` event [is related to ](http://www.w3.org/TR/html5/embedded-content-0.html#event-media-playing) `readyState` and was removed as part of the fix for #7.

**Comment by tc0312** [comment]
Does most CDMs support partially encrypted content? Should EME support this use case?

To optimize for video start time, some might encode the beginning of a video in clear, so playback could start without waiting for DRM.

In this case, waitingforkey event is expected by the normal playback workflow. it would be the best if CDM can fire a resumeFromWaitForKey event to explicitly tell applications that playback has resumed.

**Comment by cpearce** [comment]
Common Encryption (CENC), which is what MP4 is encrypted with, supports partial encryption.

What use case does "waitForKey" support that can't be inferred from the MediaKeySession.keyStatuses and keystatuseschanged event?

**Comment by ddorwin** [comment]
>Do most CDMs support partially encrypted content? Should EME support this use case?

Partially-encrypted content is a container feature. Both currently supported formats, WebM and BMFF/CENC support partial encryption using either different tracks or at the block or byte range level.

Note: Some implementations may not start playback of potentially encrypted streams, even of unencrypted frames, until a `MediaKeys` has been attached. The reason is that the decoders/pipeline need to be selected first. Such implementations should start playback once the `MediaKeys` is attached, regardless of whether any keys have been added.

>In this case, waitingforkey event is expected by the normal playback workflow.

`waitingforkey` would only be fired if playback reached (or was within a few frames of) the encrypted block. Thus, if you saw `waitingforkey` in this case, your user probably experienced an interruption because the key was not received in time. This should be a rare exception rather than the normal playback workflow.

**Comment by tc0312** [comment]
> What use case does "waitForKey" support that can't be inferred from the MediaKeySession.keyStatuses and keystatuseschanged event?

Key status doesn't necessarily map to the CDM's state. If the application loaded a wrong unused key to the CDM, it would show up as "usable" but yet the playback is stalled.

In my opinion, EME as an API should provide a way to let the application to detect it for robustness. Even if it's not a major use case.

**Comment by tc0312** [comment]
After some more thought, providing the resume event doesn't help application to detect the wrong key case.

From applications' perspective, it would be great if the CDM can fire another "waitForKey" event after MediaKeySession::update() if playback is already blocked and that update() call doesn't unblock playback. Application can listen for that event and know for sure it has loaded the wrong key. Video service provider then knows their video stream or DRM service have a problem and investigate.

I agree that this's an edge/error case, but I believe it's important to provide an API which applications can implement robust error handling.

**Comment by ddorwin** [comment]
I think that is already the behavior (mostly).

The Attempt to Resume Playback If Necessary algorithm runs the Encrypted Block Encountered algorithm, which I believe would get to the "Run the queue a "waitingforkey" event algorithm on the media element" step.

However, the call sites for "Attempt to Resume Playback If Necessary algorithm" say "The user agent may choose to skip this step if it knows resuming will fail." Thus, the behavior could be inconsistent.

@tc0312, if your original issue is obsolete, perhaps we should close this and open a new bug on whether a) the subsequent events are desirable and b) we should make the behavior consistent. Does that work for you?

**Comment by ddorwin** [comment]
I filed #98 per my comment above. I think that addresses the current scope of this issue.
