### ISSUE TITLE
Provide guidance on object and CDM lifetime

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#43]
Moving https://www.w3.org/Bugs/Public/show_bug.cgi?id=24771 for tracking. See that bug for details. Some changes to the original proposal may be necessary due to changes in the year since it was made.

**Comment by mwatson2** [comment]
I have addressed this fairly economically. Please re-open if you feel more detail is required.

It turns out the rule for destruction of a CDM instance is logically implied by the MediaKeys rule and MediaKeySession rule, so I have addressed that with a note under MediaKeySession.

There is only one instance where we refer to the "MediaKeys object that created this session" and that is where we need to identify the media element that some procedure should influence. If the MediaKeys object has been deleted there is obviously no media element, so I did not add further clarification here.
