### ISSUE TITLE
Remove 'persistent-usage-record' MediaKeySessionType

### ISSUE THREAD

**Issue by gregwfreedman** [w3c/encrypted-media#480]
For various reasons, Netflix has decided not to use the 'persistent-usage-record' MediaKeySessionType moving forward. Before removing this feature from the latest Editor's Draft, I want to know if there's any interest outside Netflix in keeping this feature.

**Comment by xhwang-chromium** [comment]
I have not heard of any site using this yet. I could add a metric to collect information about usage in Chromium.

**Comment by mounirlamouri** [comment]
Removing the agenda label as it was discussed at the January meeting.

**Comment by xhwang-chromium** [comment]
gregwfreedman: I checked Chrome's metrics and there's no usage of `persistent-usage-record` session type at all so far. Also I've not heard any other interest in using/keeping this feature. Since we also discussed about this in the January meeting without any objections, I think it's safe to remove it from the latest Editor's Draft.

**Comment by chrisn** [comment]
I see that we still have tests for this feature, obviously these fail because there are no implementations. Could we remove the tests?

* https://github.com/web-platform-tests/wpt/blob/master/encrypted-media/clearkey-mp4-playback-persistent-usage-record-events.https.html
* https://github.com/web-platform-tests/wpt/blob/master/encrypted-media/clearkey-mp4-playback-persistent-usage-record.https.html
* https://github.com/web-platform-tests/wpt/blob/master/encrypted-media/clearkey-mp4-playback-retrieve-persistent-usage-record.https.html
* https://github.com/web-platform-tests/wpt/blob/master/encrypted-media/drm-mp4-playback-persistent-usage-record-events.https.html
* https://github.com/web-platform-tests/wpt/blob/master/encrypted-media/drm-mp4-playback-persistent-usage-record.https.html
* https://github.com/web-platform-tests/wpt/blob/master/encrypted-media/drm-mp4-playback-retrieve-persistent-usage-record.https.html

**Comment by xhwang-chromium** [comment]
Thanks for catching that. Yes we should remove them!
