### ISSUE TITLE
Update registry pages to match the current spec

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#60]
The `"cenc"` and `"keyids"` pages currently refer to passing initData `createSession()`. These need to be updated to refer to `generateRequest()`. There may be other issues.

**Comment by jdsmith3000** [comment]
Agreed.

**Comment by ddorwin** [comment]
@mwatson2 can you take this and implement it so it's done before we start doing surgery on the registry (i.e. #105)?

**Comment by mwatson2** [comment]
Sure. I don't think either of these specifications need to refer to specific algorithms / methods in the main specification. They are defining formats which have a well-defined name ("Initialization Data") referred to in the main spec. For the CENC one, it should be sufficient to say that the case of no recognized SystemID corresponds to "not supported by the CDM", which is a case already handled by the main specification algorithm (otherwise it looks like a monkey-patch).
