### ISSUE TITLE
Define key ID sort order

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#69]
The fix for #39 added the text "sorted by key ID."

Since a key ID is just an array of bytes, we should clarify what it means to be sorted by key ID. Are bytes compared from byte 0 to N or N to 0? What if the key IDs have different lengths?

This also depends on defining the representation (#68).

**Comment by ddorwin** [comment]
We should probably address #75 first.

**Comment by cpearce-mozilla** [comment]
FWIW, [I'm implementing Firefox's key ID sort order](https://bugzilla.mozilla.org/show_bug.cgi?id=1223980) to copy Chromium's [MediaKeyStatusMap::MapEntry::compareLessThan](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/modules/encryptedmedia/MediaKeyStatusMap.cpp&sq=package:chromium&l=37), i.e. just do a memcmp on the keyIDs' bytes.

**Comment by mwatson2** [comment]
I think we could address this one independently of #75, since we will need to specify an order either way. I propose adding the following to the current "sorted by Key ID":

"where for Key IDs *A* and *B* of lengths *n* and *m* respectively with *n* <= *m* then we define *A* < *B* if and only if the first *n* octets of *A* are less in lexicographical order than the first *n* octets of *B* or those octets are equal and *n* < *m*."

**Comment by cpearce-mozilla** [comment]
Sounds good to me.

**Comment by mwatson2** [comment]
If there are no further comments on this issue, I will implement my proposal above/
