### ISSUE TITLE
MediaKeyStatusMap: iterable declaration has unexpected behavior; ForEachCallback definition is incorrect

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#75]
The spec currently has:
>`callback ForEachCallback = void (BufferSource keyId, MediaKeyStatus status);`

First, values always come before keys in forEach callbacks (modulo what appear to be [bugs](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28978) in Web IDL). Thus, `ForEachCallback`'s parameters should be reversed so the "value" is first and the "key" is second.

<br/>However, I don’t believe either signature is currently possible because `MediaKeyStatusMap` has an `iterable` declaration. Based on my interpretation (see [bug 28978](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28978) and item 2 in [bug 28979](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28979)), the callback would be called with `index, [keyId, status]`. (This may not be the correct ordering - see [bug 28978](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28978).)

In addition, we may not need to explicitly specify `forEach`. See item 4 in [bug 28979](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28979)). Given the complexity, it would probably still be a good idea to explain the format in a non-normative note.

<br/>If our intent is for `MediaKeyStatusMap` to be like a Map, the [iterable declaration](https://heycam.github.io/webidl/#dfn-iterable-declaration) breaks this. We may want to just remove the iterable declaration and specify the "entries", "keys", "values" and `@@iterator` methods explicitly. That would allow us to have a `ForEachCallback` that behaves the same as a `Map`.

<br/>Note: If we continue to use an iterable declaration, we may also want to rework the prose to explicitly identify the “key” and “value” and reference https://heycam.github.io/webidl/#dfn-value-pairs-to-iterate-over like https://fetch.spec.whatwg.org/#headers-class.

**Comment by ddorwin** [comment]
In addition, the iterable declaration results in unexpected behavior for other methods. For example, in the ECMAScript language binding, `keys()` returns an iterator over the indexes (0, 1, 2, ...) and `values()` returns an iterator over the pair of values (`[status, keyId]`).

**Comment by ddorwin** [comment]
Assuming my interpretation is correct and there are no binding advantages to using such a declaration, we should probably remove the iterable declaration added for #39 and manually define the desired methods. @bzbarsky, do you have any comments or suggestions?

In the meantime, we should probably add an issue indicating that it is an open question whether to use iterable declaration and that the currently defined behavior is probably not what an author would expect.

**Comment by bzbarsky** [comment]
If you want this to be like a Map, why isn't it `maplike` instead of `iterable`?

**Comment by bzbarsky** [comment]
Oh, I see why.  Because you want to use the bytes of a `BufferSource` as a key, but that doesn't match ES `Map` behavior; a `Map` would use the object identity as the key.

In that case, an iterable with a keytype and valuetype does seem like what you want.  To the extent that the behavior in that situation isn't what one would want, those are clearly bugs in the spec due to algorithms not getting updated when value pair iterators were added.  In particular, `forEach` should obviously be passing in the key and value in the value pair case.  /cc @heycam in case I'm wrong about the intent here.

**Comment by mwatson2** [comment]
If I understand correctly, WebIDL is going to take care of the forEach definition for iterable (the first note in https://heycam.github.io/webidl/#idl-iterable needs to be updated).

We have a problem if the WebIDL definition of forEach for an iterable or value pairs does not align with the way we would like our object to behave, which is like an ES Map.

And it seems the material in WebIDL is new and unstable (at least there is bug 28979).

Should we remove our forEach definition for the moment and wait for WebIDL to stabilize ? If it turns out that forEach for a value pair iterable does not align with forEach for ES Maps, then we'll need to drop the iterable and define all the methods ourselves.

**Comment by ddorwin** [comment]
@heycam, is the problematic behavior of `iterable` caused by bugs in the algorithms as @bzbarsky said on July 20th or is this the intended behavior?

**Comment by bzbarsky** [comment]
Note that I started a thread on `forEach` behavior for iterables at https://lists.w3.org/Archives/Public/public-script-coord/2015OctDec/0039.html but no responses so far.

**Comment by ddorwin** [comment]
Thanks, @bzbarsky. Does your email cover [part of]  [bug 28978](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28978) and [bug 28979](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28979)? Does it make sense to cross-reference the thread and bugs? I can ask on thread, but it probably makes more sense for you to accurately describe the overlap or reference the bugs where it makes sense. (Please cc me if you reply to the thread.)

Even if `forEach` is resolved in a favorable way, would `keys()` still return an iterator over the indexes as I said in my [second comment](#issuecomment-123094014) above?

**Comment by bzbarsky** [comment]
> Does your email cover [part of] bug 28978 and bug 28979?

My mail doesn't really cover https://www.w3.org/Bugs/Public/show_bug.cgi?id=28978 per se, but that clearly needs to be addressed as part of the cleanup, yes.  It covers the `forEach`-related parts of <https://www.w3.org/Bugs/Public/show_bug.cgi?id=28979>, I believe.

> would `keys()` still return an iterator over the indexes 

@heycam has pending spec updates to make single-type iterables behave more like `Set` in terms of `keys()` behavior (at least as long as there is no indexed getter; if there is one things are a bit more up in the air) and make two-type iterables behave more like `Map`.   With those updates, for a single-type iterable `keys()` and `values()` would both return iterators that return the same thing and for a two-type iterable `keys()` returns an iterator over the keys and `values()` returns an iterator over the values.

That's the behavior you presumably want here, since the only reason you're not using maplike is because you really want a value type, not an object type, for the key, but typed arrays are object types...

That said, your prose will need to define the value pairs to iterate a bit carefully (e.g. what the actual BufferSource objects are; you obviously can't have an actual BufferSource object, since that's not a concrete type at all but a union type).

**Comment by paulbrucecotton** [comment]
@bzbarsky or @heycam - Can you give us an update on when or how we can move this issue forward?

**Comment by bzbarsky** [comment]
Once https://github.com/heycam/webidl/pull/72 gets merged in you should have forEach doing what you want, I think.  Hopefully pretty soon now.

**Comment by ddorwin** [comment]
https://github.com/heycam/webidl/pull/72 has been merged. We need to review the current text to determine suitability and whether the issues described above have been resolved.

**Comment by paulbrucecotton** [comment]
>We need to review the current text to determine suitability and whether the issues described above have been resolved.

@ddorwin: What is stopping us closing this bug?

**Comment by mwatson2** [comment]
I believe this has been solved in WebIDL, which now defines [`forEach`](https://heycam.github.io/webidl/#es-forEach) for a value pair iterator to behave like the ES6 Map one (i.e. the opposite argument order to the callback to our current definition).

So, I propose we simply remove our `forEach` definition.

**Comment by mwatson2** [comment]
Please review [this PR](https://github.com/w3c/encrypted-media/pull/209).

**Comment by ddorwin** [comment]
The PR looks good, but the example needs to be updated.

The [WebIDL Level 1 CR](https://www.w3.org/TR/WebIDL-1/) does **not** have the `forEach` fixes that the [ED](https://heycam.github.io/webidl/) does. Since these are breaking changes to Web IDL, these should be applied to the CR. @travisleithead, can you help integrate the `forEach`-related changes into the CR draft?

@plehegar, FYI on the process issue that affects EME.
